import type { Task } from "./types";

// Ручной контент для 5–11 классов: логика, чтение и окружающий мир.
// Математика этих классов генерируется в generated.ts.
// Первый проход — темы наполнены базовыми заданиями, дальше дорабатываем.

// ── ЛОГИКА ─────────────────────────────────────────────
const LOGIC: Task[] = [
  // 5 класс
  {
    id: "g-log5-a", type: "number_input", subject: "logic", topic: "log5", grade: 5,
    difficulty: 2, free: true,
    prompt: { ru: "Продолжи ряд: 3, 6, 12, 24, ?", ky: "Катарды улант: 3, 6, 12, 24, ?" },
    answer: 48,
    explanation: { ru: "Каждое число в 2 раза больше: 24 × 2 = 48.", ky: "Ар бир сан 2 эсе чоң: 24 × 2 = 48." },
  },
  {
    id: "g-log5-b", type: "single_choice", subject: "logic", topic: "log5", grade: 5,
    difficulty: 2, free: true,
    prompt: { ru: "Птица — небо, рыба — ?", ky: "Куш — асман, балык — ?" },
    options: [{ ru: "вода", ky: "суу" }, { ru: "земля", ky: "жер" }, { ru: "огонь", ky: "от" }],
    correctIndex: 0,
    explanation: { ru: "Птица живёт в небе, рыба — в воде.", ky: "Куш асманда, балык сууда жашайт." },
  },
  {
    id: "g-log5-c", type: "single_choice", subject: "logic", topic: "log5", grade: 5,
    difficulty: 2, free: false,
    prompt: { ru: "Какое число лишнее: 2, 4, 6, 9?", ky: "Кайсы сан ашык: 2, 4, 6, 9?" },
    options: [{ ru: "2", ky: "2" }, { ru: "4", ky: "4" }, { ru: "6", ky: "6" }, { ru: "9", ky: "9" }],
    correctIndex: 3,
    explanation: { ru: "9 — нечётное, остальные чётные.", ky: "9 — так, калгандары жуп." },
  },
  // 6 класс
  {
    id: "g-log6-a", type: "number_input", subject: "logic", topic: "log6", grade: 6,
    difficulty: 3, free: true,
    prompt: { ru: "Продолжи ряд: 1, 1, 2, 3, 5, 8, ?", ky: "Катарды улант: 1, 1, 2, 3, 5, 8, ?" },
    answer: 13,
    explanation: { ru: "Каждое число — сумма двух предыдущих: 5 + 8 = 13.", ky: "Ар бир сан мурунку экөөнүн суммасы: 5 + 8 = 13." },
  },
  {
    id: "g-log6-b", type: "number_input", subject: "logic", topic: "log6", grade: 6,
    difficulty: 3, free: true,
    prompt: { ru: "Продолжи ряд: 1, 3, 6, 10, ?", ky: "Катарды улант: 1, 3, 6, 10, ?" },
    answer: 15,
    explanation: { ru: "Прибавляем по порядку 2, 3, 4, 5: 10 + 5 = 15.", ky: "Ирети менен 2, 3, 4, 5 кошобуз: 10 + 5 = 15." },
  },
  {
    id: "g-log6-c", type: "single_choice", subject: "logic", topic: "log6", grade: 6,
    difficulty: 3, free: false,
    prompt: { ru: "День — ночь, лето — ?", ky: "Күн — түн, жай — ?" },
    options: [{ ru: "зима", ky: "кыш" }, { ru: "весна", ky: "жаз" }, { ru: "осень", ky: "күз" }],
    correctIndex: 0,
    explanation: { ru: "День и ночь — противоположности, как лето и зима.", ky: "Күн менен түн карама-каршы, жай менен кыш сыяктуу." },
  },
  // 7 класс
  {
    id: "g-log7-a", type: "single_choice", subject: "logic", topic: "log7", grade: 7,
    difficulty: 3, free: true,
    prompt: { ru: "Если A > B и B > C, то A … C", ky: "Эгер A > B жана B > C болсо, A … C" },
    options: [{ ru: "больше", ky: "чоң" }, { ru: "меньше", ky: "кичине" }, { ru: "равно", ky: "барабар" }],
    correctIndex: 0,
    explanation: { ru: "Если A больше B, а B больше C, то A больше C.", ky: "A B'дан чоң, B C'дан чоң болсо, A C'дан чоң." },
  },
  {
    id: "g-log7-b", type: "number_input", subject: "logic", topic: "log7", grade: 7,
    difficulty: 3, free: true,
    prompt: { ru: "Продолжи ряд: 2, 6, 18, 54, ?", ky: "Катарды улант: 2, 6, 18, 54, ?" },
    answer: 162,
    explanation: { ru: "Каждое число в 3 раза больше: 54 × 3 = 162.", ky: "Ар бир сан 3 эсе чоң: 54 × 3 = 162." },
  },
  {
    id: "g-log7-c", type: "single_choice", subject: "logic", topic: "log7", grade: 7,
    difficulty: 3, free: false,
    prompt: { ru: "Что лишнее: квадрат, круг, треугольник, куб?", ky: "Эмне ашык: квадрат, тегерек, үч бурчтук, куб?" },
    options: [{ ru: "квадрат", ky: "квадрат" }, { ru: "круг", ky: "тегерек" }, { ru: "треугольник", ky: "үч бурчтук" }, { ru: "куб", ky: "куб" }],
    correctIndex: 3,
    explanation: { ru: "Куб — объёмная фигура, остальные плоские.", ky: "Куб — көлөмдүү фигура, калгандары жалпак." },
  },
  // 8 класс
  {
    id: "g-log8-a", type: "number_input", subject: "logic", topic: "log8", grade: 8,
    difficulty: 3, free: true,
    prompt: { ru: "Продолжи ряд: 1, 2, 4, 7, 11, ?", ky: "Катарды улант: 1, 2, 4, 7, 11, ?" },
    answer: 16,
    explanation: { ru: "Разности растут: +1, +2, +3, +4, +5. 11 + 5 = 16.", ky: "Айырмалар өсөт: +1, +2, +3, +4, +5. 11 + 5 = 16." },
  },
  {
    id: "g-log8-b", type: "number_input", subject: "logic", topic: "log8", grade: 8,
    difficulty: 3, free: true,
    prompt: {
      ru: "Множества A = {1, 2, 3} и B = {2, 3, 4}. Сколько общих элементов?",
      ky: "A = {1, 2, 3} жана B = {2, 3, 4} көптүктөрү. Канча жалпы элемент бар?",
    },
    answer: 2,
    explanation: { ru: "Общие элементы — 2 и 3, их два.", ky: "Жалпы элементтер — 2 жана 3, экөө." },
  },
  {
    id: "g-log8-c", type: "single_choice", subject: "logic", topic: "log8", grade: 8,
    difficulty: 3, free: false,
    prompt: {
      ru: "«Неверно, что все кошки чёрные». Что из этого следует?",
      ky: "«Бардык мышыктар кара» деген туура эмес. Мындан эмне келип чыгат?",
    },
    options: [
      { ru: "Есть хотя бы одна не чёрная кошка", ky: "Жок дегенде бир кара эмес мышык бар" },
      { ru: "Все кошки не чёрные", ky: "Бардык мышыктар кара эмес" },
      { ru: "Чёрных кошек нет", ky: "Кара мышыктар жок" },
    ],
    correctIndex: 0,
    explanation: { ru: "Отрицание «все» — это «существует хотя бы одна, для которой неверно».", ky: "«Бардык» дегендин тескериси — «жок дегенде бирөө туура келбейт»." },
  },
  // 9 класс
  {
    id: "g-log9-a", type: "number_input", subject: "logic", topic: "log9", grade: 9,
    difficulty: 3, free: true,
    prompt: { ru: "Сколькими способами можно расставить 3 книги на полке?", ky: "3 китепти текчеге канча жол менен коюуга болот?" },
    answer: 6,
    explanation: { ru: "3! = 3 × 2 × 1 = 6.", ky: "3! = 3 × 2 × 1 = 6." },
  },
  {
    id: "g-log9-b", type: "number_input", subject: "logic", topic: "log9", grade: 9,
    difficulty: 3, free: true,
    prompt: {
      ru: "Сколько двузначных чисел можно составить из цифр 1, 2, 3 без повторов?",
      ky: "1, 2, 3 цифраларынан кайталанбаган канча эки орундуу сан түзүүгө болот?",
    },
    answer: 6,
    explanation: { ru: "Первая цифра — 3 варианта, вторая — 2. 3 × 2 = 6.", ky: "Биринчи цифра — 3 вариант, экинчиси — 2. 3 × 2 = 6." },
  },
  {
    id: "g-log9-c", type: "number_input", subject: "logic", topic: "log9", grade: 9,
    difficulty: 3, free: false,
    prompt: { ru: "Монету бросают дважды. Сколько всего исходов?", ky: "Тыйынды эки жолу ыргытат. Бардыгы канча жыйынтык?" },
    answer: 4,
    explanation: { ru: "Каждый бросок — 2 варианта: 2 × 2 = 4.", ky: "Ар бир ыргытуу — 2 вариант: 2 × 2 = 4." },
  },
  // 10 класс
  {
    id: "g-log10-a", type: "single_choice", subject: "logic", topic: "log10", grade: 10,
    difficulty: 3, free: true,
    prompt: {
      ru: "«Если идёт дождь, земля мокрая». Земля сухая. Значит дождь…",
      ky: "«Жамгыр жааса, жер нымдуу». Жер кургак. Демек жамгыр…",
    },
    options: [{ ru: "не идёт", ky: "жаабайт" }, { ru: "идёт", ky: "жаайт" }, { ru: "неизвестно", ky: "белгисиз" }],
    correctIndex: 0,
    explanation: { ru: "Если бы шёл дождь, земля была бы мокрой. Она сухая — значит дождя нет.", ky: "Жамгыр жааса, жер нымдуу болмок. Ал кургак — демек жамгыр жаабайт." },
  },
  {
    id: "g-log10-b", type: "single_choice", subject: "logic", topic: "log10", grade: 10,
    difficulty: 3, free: true,
    prompt: { ru: "Истинно ли высказывание: «2 + 2 = 4 И 3 > 5»?", ky: "«2 + 2 = 4 ЖАНА 3 > 5» деген пикир чынбы?" },
    options: [{ ru: "Ложь", ky: "Жалган" }, { ru: "Истина", ky: "Чын" }],
    correctIndex: 0,
    explanation: { ru: "«И» истинно, только если обе части верны. 3 > 5 — ложь.", ky: "«ЖАНА» эки бөлүк тең чын болгондо гана чын. 3 > 5 — жалган." },
  },
  {
    id: "g-log10-c", type: "single_choice", subject: "logic", topic: "log10", grade: 10,
    difficulty: 3, free: false,
    prompt: { ru: "Отрицание фразы «Все студенты сдали экзамен» — это…", ky: "«Бардык студенттер экзамен тапшырды» деген сүйлөмдүн тескериси…" },
    options: [
      { ru: "Хотя бы один не сдал", ky: "Жок дегенде бирөө тапшырган жок" },
      { ru: "Никто не сдал", ky: "Эч ким тапшырган жок" },
      { ru: "Все не сдали", ky: "Баары тапшырган жок" },
    ],
    correctIndex: 0,
    explanation: { ru: "Отрицание «все» — «существует хотя бы один, кто не…».", ky: "«Бардык» дегендин тескериси — «жок дегенде бирөө …кылган жок»." },
  },
  // 11 класс
  {
    id: "g-log11-a", type: "number_input", subject: "logic", topic: "log11", grade: 11,
    difficulty: 3, free: true,
    prompt: { ru: "Чему равна сумма углов треугольника (в градусах)?", ky: "Үч бурчтуктун бурчтарынын суммасы канчага барабар (градуста)?" },
    answer: 180,
    explanation: { ru: "Сумма углов любого треугольника равна 180°.", ky: "Ар кандай үч бурчтуктун бурчтарынын суммасы 180°." },
  },
  {
    id: "g-log11-b", type: "single_choice", subject: "logic", topic: "log11", grade: 11,
    difficulty: 3, free: true,
    prompt: { ru: "Верно ли: «Если число делится на 4, то оно делится на 2»?", ky: "«Сан 4кө бөлүнсө, ал 2ге бөлүнөт» деген туурабы?" },
    options: [{ ru: "Да", ky: "Ооба" }, { ru: "Нет", ky: "Жок" }],
    correctIndex: 0,
    explanation: { ru: "4 = 2 × 2, поэтому любое кратное 4 кратно и 2.", ky: "4 = 2 × 2, ошондуктан 4кө эселүү сан 2ге да эселүү." },
  },
  {
    id: "g-log11-c", type: "number_input", subject: "logic", topic: "log11", grade: 11,
    difficulty: 3, free: false,
    prompt: { ru: "Сколько диагоналей у пятиугольника?", ky: "Беш бурчтуктун канча диагоналы бар?" },
    answer: 5,
    explanation: { ru: "Формула n(n−3)/2 = 5 × 2 / 2 = 5.", ky: "n(n−3)/2 = 5 × 2 / 2 = 5." },
  },
  // ── Логика: дополнительные задания (второй проход) ──
  {
    id: "g-log5-d", type: "number_input", subject: "logic", topic: "log5", grade: 5,
    difficulty: 2, free: true,
    prompt: { ru: "Продолжи ряд: 5, 10, 20, 40, ?", ky: "Катарды улант: 5, 10, 20, 40, ?" },
    answer: 80,
    explanation: { ru: "Каждое число в 2 раза больше: 40 × 2 = 80.", ky: "Ар бир сан 2 эсе чоң: 40 × 2 = 80." },
  },
  {
    id: "g-log5-e", type: "single_choice", subject: "logic", topic: "log5", grade: 5,
    difficulty: 2, free: false,
    prompt: { ru: "День — неделя, месяц — ?", ky: "Күн — жума, ай — ?" },
    options: [{ ru: "год", ky: "жыл" }, { ru: "час", ky: "саат" }, { ru: "минута", ky: "мүнөт" }],
    correctIndex: 0,
    explanation: { ru: "Неделя состоит из дней, год — из месяцев.", ky: "Жума күндөрдөн, жыл айлардан турат." },
  },
  {
    id: "g-log6-d", type: "number_input", subject: "logic", topic: "log6", grade: 6,
    difficulty: 3, free: true,
    prompt: { ru: "Продолжи ряд: 2, 5, 10, 17, ?", ky: "Катарды улант: 2, 5, 10, 17, ?" },
    answer: 26,
    explanation: { ru: "Разности 3, 5, 7, 9: 17 + 9 = 26.", ky: "Айырмалар 3, 5, 7, 9: 17 + 9 = 26." },
  },
  {
    id: "g-log6-e", type: "single_choice", subject: "logic", topic: "log6", grade: 6,
    difficulty: 3, free: false,
    prompt: { ru: "Какое число лишнее: 9, 16, 25, 30?", ky: "Кайсы сан ашык: 9, 16, 25, 30?" },
    options: [{ ru: "9", ky: "9" }, { ru: "16", ky: "16" }, { ru: "25", ky: "25" }, { ru: "30", ky: "30" }],
    correctIndex: 3,
    explanation: { ru: "9, 16, 25 — квадраты чисел, а 30 нет.", ky: "9, 16, 25 — сандардын квадраттары, 30 андай эмес." },
  },
  {
    id: "g-log7-d", type: "number_input", subject: "logic", topic: "log7", grade: 7,
    difficulty: 3, free: true,
    prompt: { ru: "Продолжи ряд: 1, 2, 6, 24, ?", ky: "Катарды улант: 1, 2, 6, 24, ?" },
    answer: 120,
    explanation: { ru: "Умножаем на 2, 3, 4, 5: 24 × 5 = 120.", ky: "2, 3, 4, 5ке көбөйтөбүз: 24 × 5 = 120." },
  },
  {
    id: "g-log7-e", type: "single_choice", subject: "logic", topic: "log7", grade: 7,
    difficulty: 3, free: false,
    prompt: { ru: "Все квадраты — прямоугольники. Верно ли обратное?", ky: "Бардык чарчылар — тик бурчтуктар. Тескериси туурабы?" },
    options: [{ ru: "Нет", ky: "Жок" }, { ru: "Да", ky: "Ооба" }],
    correctIndex: 0,
    explanation: { ru: "Не каждый прямоугольник — квадрат.", ky: "Ар бир тик бурчтук чарчы эмес." },
  },
  {
    id: "g-log8-d", type: "number_input", subject: "logic", topic: "log8", grade: 8,
    difficulty: 3, free: true,
    prompt: {
      ru: "В классе 25 учеников. 15 играют в футбол, 12 в шахматы, 5 — и в то, и в другое. Сколько играют в футбол, но не в шахматы?",
      ky: "Класста 25 окуучу. 15 футбол ойнойт, 12 шахмат, 5 — экөөнү тең. Канчасы футбол ойнойт, бирок шахмат эмес?",
    },
    answer: 10,
    explanation: { ru: "15 − 5 = 10.", ky: "15 − 5 = 10." },
  },
  {
    id: "g-log8-e", type: "number_input", subject: "logic", topic: "log8", grade: 8,
    difficulty: 3, free: false,
    prompt: {
      ru: "Множества A = {1,2,3,4} и B = {3,4,5}. Сколько элементов в объединении A и B?",
      ky: "A = {1,2,3,4} жана B = {3,4,5}. A менен B бириккенде канча элемент?",
    },
    answer: 5,
    explanation: { ru: "Объединение: {1,2,3,4,5} — пять элементов.", ky: "Бириктирүү: {1,2,3,4,5} — беш элемент." },
  },
  {
    id: "g-log9-d", type: "number_input", subject: "logic", topic: "log9", grade: 9,
    difficulty: 3, free: true,
    prompt: { ru: "Сколькими способами можно расставить 4 книги на полке?", ky: "4 китепти текчеге канча жол менен коюуга болот?" },
    answer: 24,
    explanation: { ru: "4! = 4 × 3 × 2 × 1 = 24.", ky: "4! = 4 × 3 × 2 × 1 = 24." },
  },
  {
    id: "g-log9-e", type: "number_input", subject: "logic", topic: "log9", grade: 9,
    difficulty: 3, free: false,
    prompt: { ru: "Игральную кость бросают дважды. Сколько всего исходов?", ky: "Оюн сөөгүн эки жолу ыргытат. Бардыгы канча жыйынтык?" },
    answer: 36,
    explanation: { ru: "6 × 6 = 36.", ky: "6 × 6 = 36." },
  },
  {
    id: "g-log10-d", type: "single_choice", subject: "logic", topic: "log10", grade: 10,
    difficulty: 3, free: true,
    prompt: { ru: "Истинно ли высказывание: «5 > 3 ИЛИ 2 > 7»?", ky: "«5 > 3 ЖЕ 2 > 7» деген пикир чынбы?" },
    options: [{ ru: "Истина", ky: "Чын" }, { ru: "Ложь", ky: "Жалган" }],
    correctIndex: 0,
    explanation: { ru: "«ИЛИ» истинно, если хотя бы одна часть верна. 5 > 3 — верно.", ky: "«ЖЕ» жок дегенде бир бөлүк чын болсо чын. 5 > 3 — чын." },
  },
  {
    id: "g-log10-e", type: "single_choice", subject: "logic", topic: "log10", grade: 10,
    difficulty: 3, free: false,
    prompt: { ru: "Отрицание высказывания «x > 5» — это…", ky: "«x > 5» пикиринин тескериси…" },
    options: [{ ru: "x ≤ 5", ky: "x ≤ 5" }, { ru: "x < 5", ky: "x < 5" }, { ru: "x ≥ 5", ky: "x ≥ 5" }],
    correctIndex: 0,
    explanation: { ru: "Отрицание «больше 5» — «меньше или равно 5».", ky: "«5тен чоң» дегендин тескериси — «5тен кичине же барабар»." },
  },
  {
    id: "g-log11-d", type: "number_input", subject: "logic", topic: "log11", grade: 11,
    difficulty: 3, free: true,
    prompt: { ru: "Сколько диагоналей у шестиугольника?", ky: "Алты бурчтуктун канча диагоналы бар?" },
    answer: 9,
    explanation: { ru: "n(n−3)/2 = 6 × 3 / 2 = 9.", ky: "n(n−3)/2 = 6 × 3 / 2 = 9." },
  },
  {
    id: "g-log11-e", type: "single_choice", subject: "logic", topic: "log11", grade: 11,
    difficulty: 3, free: false,
    prompt: { ru: "Верно ли: «Если число делится на 6, то оно делится на 3»?", ky: "«Сан 6га бөлүнсө, ал 3кө бөлүнөт» деген туурабы?" },
    options: [{ ru: "Да", ky: "Ооба" }, { ru: "Нет", ky: "Жок" }],
    correctIndex: 0,
    explanation: { ru: "6 = 2 × 3, поэтому кратное 6 кратно и 3.", ky: "6 = 2 × 3, ошондуктан 6га эселүү сан 3кө да эселүү." },
  },
];

// ── ЧТЕНИЕ / ЯЗЫК ──────────────────────────────────────
const READING: Task[] = [
  // 5 класс — части речи
  {
    id: "g-read5-a", type: "single_choice", subject: "reading", topic: "read5", grade: 5,
    difficulty: 2, free: true,
    prompt: { ru: "Найди существительное", ky: "Зат атоочту тап" },
    options: [{ ru: "бежит", ky: "чуркайт" }, { ru: "стол", ky: "үстөл" }, { ru: "быстро", ky: "тез" }],
    correctIndex: 1,
    explanation: { ru: "«Стол» — предмет, отвечает на вопрос «что?».", ky: "«Үстөл» — зат, «эмне?» суроосуна жооп берет." },
  },
  {
    id: "g-read5-b", type: "single_choice", subject: "reading", topic: "read5", grade: 5,
    difficulty: 2, free: true,
    prompt: { ru: "Найди глагол", ky: "Этишти тап" },
    options: [{ ru: "красивый", ky: "кооз" }, { ru: "читать", ky: "окуу" }, { ru: "книга", ky: "китеп" }],
    correctIndex: 1,
    explanation: { ru: "«Читать» — действие, отвечает на вопрос «что делать?».", ky: "«Окуу» — иш-аракет, «эмне кылуу?» суроосуна жооп берет." },
  },
  {
    id: "g-read5-c", type: "single_choice", subject: "reading", topic: "read5", grade: 5,
    difficulty: 2, free: false,
    prompt: { ru: "Найди прилагательное", ky: "Сын атоочту тап" },
    options: [{ ru: "дом", ky: "үй" }, { ru: "зелёный", ky: "жашыл" }, { ru: "прыгать", ky: "секирүү" }],
    correctIndex: 1,
    explanation: { ru: "«Зелёный» — признак предмета, отвечает на вопрос «какой?».", ky: "«Жашыл» — заттын белгиси, «кандай?» суроосуна жооп берет." },
  },
  // 6 класс — синонимы/антонимы
  {
    id: "g-read6-a", type: "single_choice", subject: "reading", topic: "read6", grade: 6,
    difficulty: 3, free: true,
    prompt: { ru: "Найди синоним к слову «храбрый»", ky: "«Эр жүрөк» сөзүнө синонимди тап" },
    options: [{ ru: "смелый", ky: "кайраттуу" }, { ru: "слабый", ky: "алсыз" }, { ru: "добрый", ky: "боорукер" }],
    correctIndex: 0,
    explanation: { ru: "«Смелый» — близкое по значению к «храбрый».", ky: "«Кайраттуу» — «эр жүрөк» менен маанилеш." },
  },
  {
    id: "g-read6-b", type: "single_choice", subject: "reading", topic: "read6", grade: 6,
    difficulty: 3, free: true,
    prompt: { ru: "Найди антоним к слову «холодный»", ky: "«Суук» сөзүнө антонимди тап" },
    options: [{ ru: "мокрый", ky: "нымдуу" }, { ru: "горячий", ky: "ысык" }, { ru: "светлый", ky: "жарык" }],
    correctIndex: 1,
    explanation: { ru: "«Горячий» — противоположность «холодного».", ky: "«Ысык» — «суук» дегендин карама-каршысы." },
  },
  {
    id: "g-read6-c", type: "number_input", subject: "reading", topic: "read6", grade: 6,
    difficulty: 3, free: false,
    prompt: { ru: "Сколько слов в предложении: «Мама мыла раму»?", ky: "«Апа терезени жууду» сүйлөмүндө канча сөз?" },
    answer: 3,
    explanation: { ru: "Слова: три.", ky: "Сөздөр: үчөө." },
  },
  // 7 класс — грамотность
  {
    id: "g-read7-a", type: "single_choice", subject: "reading", topic: "read7", grade: 7,
    difficulty: 3, free: true,
    prompt: { ru: "Найди лишнее (не родственное) слово", ky: "Ашык (тектеш эмес) сөздү тап" },
    options: [{ ru: "лес", ky: "токой" }, { ru: "лесной", ky: "токойлуу" }, { ru: "лестница", ky: "тепкич" }, { ru: "лесник", ky: "токойчу" }],
    correctIndex: 2,
    explanation: { ru: "«Лестница» не связана с «лесом» по смыслу.", ky: "«Тепкич» «токой» менен маанилеш эмес." },
  },
  {
    id: "g-read7-b", type: "single_choice", subject: "reading", topic: "read7", grade: 7,
    difficulty: 3, free: true,
    prompt: { ru: "Найди синоним к слову «большой»", ky: "«Чоң» сөзүнө синонимди тап" },
    options: [{ ru: "огромный", ky: "эбегейсиз" }, { ru: "маленький", ky: "кичине" }, { ru: "узкий", ky: "тар" }],
    correctIndex: 0,
    explanation: { ru: "«Огромный» — близко по значению к «большой».", ky: "«Эбегейсиз» — «чоң» менен маанилеш." },
  },
  {
    id: "g-read7-c", type: "number_input", subject: "reading", topic: "read7", grade: 7,
    difficulty: 3, free: false,
    prompt: { ru: "Сколько слов в предложении: «Осень наступила рано»?", ky: "«Күз эрте келди» сүйлөмүндө канча сөз?" },
    answer: 3,
    explanation: { ru: "Слова: три.", ky: "Сөздөр: үчөө." },
  },
  // 8 класс — синтаксис
  {
    id: "g-read8-a", type: "single_choice", subject: "reading", topic: "read8", grade: 8,
    difficulty: 3, free: true,
    prompt: { ru: "Найди подлежащее в предложении «Дети играют»", ky: "«Балдар ойношот» сүйлөмүндө ээни тап" },
    options: [{ ru: "дети", ky: "балдар" }, { ru: "играют", ky: "ойношот" }],
    correctIndex: 0,
    explanation: { ru: "«Дети» — подлежащее, отвечает на вопрос «кто?».", ky: "«Балдар» — ээ, «ким?» суроосуна жооп берет." },
  },
  {
    id: "g-read8-b", type: "number_input", subject: "reading", topic: "read8", grade: 8,
    difficulty: 3, free: true,
    prompt: {
      ru: "Сколько грамматических основ в предложении: «Солнце светит, птицы поют»?",
      ky: "«Күн жаркырайт, куштар сайрайт» сүйлөмүндө канча грамматикалык негиз бар?",
    },
    answer: 2,
    explanation: { ru: "Две основы: «солнце светит» и «птицы поют».", ky: "Эки негиз: «күн жаркырайт» жана «куштар сайрайт»." },
  },
  {
    id: "g-read8-c", type: "single_choice", subject: "reading", topic: "read8", grade: 8,
    difficulty: 3, free: false,
    prompt: { ru: "Найди сказуемое в предложении «Ветер шумит»", ky: "«Шамал улуйт» сүйлөмүндө баяндоочту тап" },
    options: [{ ru: "ветер", ky: "шамал" }, { ru: "шумит", ky: "улуйт" }],
    correctIndex: 1,
    explanation: { ru: "«Шумит» — сказуемое, отвечает на вопрос «что делает?».", ky: "«Улуйт» — баяндооч, «эмне кылат?» суроосуна жооп берет." },
  },
  // 9 класс — значение слов
  {
    id: "g-read9-a", type: "single_choice", subject: "reading", topic: "read9", grade: 9,
    difficulty: 3, free: true,
    prompt: { ru: "Найди антоним к слову «щедрый»", ky: "«Жоомарт» сөзүнө антонимди тап" },
    options: [{ ru: "скупой", ky: "сараң" }, { ru: "добрый", ky: "боорукер" }, { ru: "богатый", ky: "бай" }],
    correctIndex: 0,
    explanation: { ru: "«Скупой» — противоположность «щедрого».", ky: "«Сараң» — «жоомарт» дегендин карама-каршысы." },
  },
  {
    id: "g-read9-b", type: "single_choice", subject: "reading", topic: "read9", grade: 9,
    difficulty: 3, free: true,
    prompt: { ru: "Найди синоним к слову «умный»", ky: "«Акылдуу» сөзүнө синонимди тап" },
    options: [{ ru: "сообразительный", ky: "тапкыч" }, { ru: "ленивый", ky: "жалкоо" }, { ru: "грустный", ky: "капалуу" }],
    correctIndex: 0,
    explanation: { ru: "«Сообразительный» близко по значению к «умный».", ky: "«Тапкыч» — «акылдуу» менен маанилеш." },
  },
  {
    id: "g-read9-c", type: "single_choice", subject: "reading", topic: "read9", grade: 9,
    difficulty: 3, free: false,
    prompt: { ru: "В каком значении слово «золотые» в «золотые руки»?", ky: "«Алтын кол» дегенде «алтын» кайсы мааниде?" },
    options: [{ ru: "переносном", ky: "өтмө" }, { ru: "прямом", ky: "түз" }],
    correctIndex: 0,
    explanation: { ru: "«Золотые руки» — умелые; слово в переносном значении.", ky: "«Алтын кол» — уста; сөз өтмө мааниде." },
  },
  // 10 класс — речь и предложение
  {
    id: "g-read10-a", type: "single_choice", subject: "reading", topic: "read10", grade: 10,
    difficulty: 3, free: true,
    prompt: { ru: "Каков тип предложения «Который час?» по цели высказывания?", ky: "«Саат канча?» сүйлөмү максаты боюнча кандай?" },
    options: [{ ru: "вопросительное", ky: "суроолуу" }, { ru: "повествовательное", ky: "жай" }, { ru: "восклицательное", ky: "илептүү" }],
    correctIndex: 0,
    explanation: { ru: "Предложение содержит вопрос — оно вопросительное.", ky: "Сүйлөмдө суроо бар — ал суроолуу." },
  },
  {
    id: "g-read10-b", type: "single_choice", subject: "reading", topic: "read10", grade: 10,
    difficulty: 3, free: true,
    prompt: { ru: "Найди местоимение", ky: "Ат атоочту тап" },
    options: [{ ru: "он", ky: "ал" }, { ru: "дом", ky: "үй" }, { ru: "красивый", ky: "кооз" }],
    correctIndex: 0,
    explanation: { ru: "«Он» — местоимение, указывает на предмет, не называя его.", ky: "«Ал» — ат атооч, затты атабай көрсөтөт." },
  },
  {
    id: "g-read10-c", type: "number_input", subject: "reading", topic: "read10", grade: 10,
    difficulty: 3, free: false,
    prompt: {
      ru: "Сколько грамматических основ в предложении «Наступила ночь, и всё стихло»?",
      ky: "«Түн кирди, баары тынчыды» сүйлөмүндө канча грамматикалык негиз бар?",
    },
    answer: 2,
    explanation: { ru: "Две основы: «наступила ночь» и «всё стихло» — сложное предложение.", ky: "Эки негиз: «түн кирди» жана «баары тынчыды» — татаал сүйлөм." },
  },
  // 11 класс — язык и текст
  {
    id: "g-read11-a", type: "single_choice", subject: "reading", topic: "read11", grade: 11,
    difficulty: 3, free: true,
    prompt: { ru: "Найди синоним к слову «начать»", ky: "«Баштоо» сөзүнө синонимди тап" },
    options: [{ ru: "приступить", ky: "киришүү" }, { ru: "закончить", ky: "бүтүрүү" }, { ru: "забыть", ky: "унутуу" }],
    correctIndex: 0,
    explanation: { ru: "«Приступить» близко по значению к «начать».", ky: "«Киришүү» — «баштоо» менен маанилеш." },
  },
  {
    id: "g-read11-b", type: "single_choice", subject: "reading", topic: "read11", grade: 11,
    difficulty: 3, free: true,
    prompt: { ru: "Найди антоним к слову «древний»", ky: "«Байыркы» сөзүнө антонимди тап" },
    options: [{ ru: "современный", ky: "азыркы" }, { ru: "старый", ky: "эски" }, { ru: "большой", ky: "чоң" }],
    correctIndex: 0,
    explanation: { ru: "«Современный» — противоположность «древнего».", ky: "«Азыркы» — «байыркы» дегендин карама-каршысы." },
  },
  {
    id: "g-read11-c", type: "single_choice", subject: "reading", topic: "read11", grade: 11,
    difficulty: 3, free: false,
    prompt: { ru: "Какое слово лишнее по смыслу?", ky: "Кайсы сөз мааниси боюнча ашык?" },
    options: [{ ru: "радость", ky: "кубаныч" }, { ru: "счастье", ky: "бакыт" }, { ru: "веселье", ky: "шаттык" }, { ru: "грусть", ky: "кайгы" }],
    correctIndex: 3,
    explanation: { ru: "«Грусть» противоположна остальным — они о радости.", ky: "«Кайгы» калгандарга карама-каршы — алар кубаныч жөнүндө." },
  },
  // ── Чтение: дополнительные задания (второй проход) ──
  {
    id: "g-read5-d", type: "single_choice", subject: "reading", topic: "read5", grade: 5,
    difficulty: 2, free: true,
    prompt: { ru: "Найди глагол", ky: "Этишти тап" },
    options: [{ ru: "окно", ky: "терезе" }, { ru: "спать", ky: "уктоо" }, { ru: "круглый", ky: "тегерек" }],
    correctIndex: 1,
    explanation: { ru: "«Спать» — действие.", ky: "«Уктоо» — иш-аракет." },
  },
  {
    id: "g-read5-e", type: "single_choice", subject: "reading", topic: "read5", grade: 5,
    difficulty: 2, free: false,
    prompt: { ru: "Найди существительное", ky: "Зат атоочту тап" },
    options: [{ ru: "зелёный", ky: "жашыл" }, { ru: "машина", ky: "машине" }, { ru: "бегать", ky: "чуркоо" }],
    correctIndex: 1,
    explanation: { ru: "«Машина» — предмет.", ky: "«Машине» — зат." },
  },
  {
    id: "g-read6-d", type: "single_choice", subject: "reading", topic: "read6", grade: 6,
    difficulty: 3, free: true,
    prompt: { ru: "Найди синоним к слову «быстрый»", ky: "«Тез» сөзүнө синонимди тап" },
    options: [{ ru: "скорый", ky: "ылдам" }, { ru: "медленный", ky: "жай" }, { ru: "тихий", ky: "тынч" }],
    correctIndex: 0,
    explanation: { ru: "«Скорый» близко по значению к «быстрый».", ky: "«Ылдам» — «тез» менен маанилеш." },
  },
  {
    id: "g-read6-e", type: "single_choice", subject: "reading", topic: "read6", grade: 6,
    difficulty: 3, free: false,
    prompt: { ru: "Найди антоним к слову «высокий»", ky: "«Бийик» сөзүнө антонимди тап" },
    options: [{ ru: "низкий", ky: "пас" }, { ru: "широкий", ky: "кең" }, { ru: "длинный", ky: "узун" }],
    correctIndex: 0,
    explanation: { ru: "«Низкий» — противоположность «высокого».", ky: "«Пас» — «бийик» дегендин карама-каршысы." },
  },
  {
    id: "g-read7-d", type: "single_choice", subject: "reading", topic: "read7", grade: 7,
    difficulty: 3, free: true,
    prompt: { ru: "Найди синоним к слову «красивый»", ky: "«Кооз» сөзүнө синонимди тап" },
    options: [{ ru: "прекрасный", ky: "сулуу" }, { ru: "страшный", ky: "коркунучтуу" }, { ru: "грустный", ky: "капалуу" }],
    correctIndex: 0,
    explanation: { ru: "«Прекрасный» близко по значению к «красивый».", ky: "«Сулуу» — «кооз» менен маанилеш." },
  },
  {
    id: "g-read7-e", type: "single_choice", subject: "reading", topic: "read7", grade: 7,
    difficulty: 3, free: false,
    prompt: { ru: "Найди лишнее (не родственное) слово", ky: "Ашык (тектеш эмес) сөздү тап" },
    options: [{ ru: "вода", ky: "суу" }, { ru: "водный", ky: "суулуу" }, { ru: "водитель", ky: "айдоочу" }, { ru: "водичка", ky: "сууча" }],
    correctIndex: 2,
    explanation: { ru: "«Водитель» не связан с «водой» по смыслу.", ky: "«Айдоочу» «суу» менен маанилеш эмес." },
  },
  {
    id: "g-read8-d", type: "single_choice", subject: "reading", topic: "read8", grade: 8,
    difficulty: 3, free: true,
    prompt: { ru: "Найди подлежащее в предложении «Птицы улетели на юг»", ky: "«Куштар түштүккө учуп кетти» сүйлөмүндө ээни тап" },
    options: [{ ru: "птицы", ky: "куштар" }, { ru: "улетели", ky: "учуп кетти" }],
    correctIndex: 0,
    explanation: { ru: "«Птицы» — подлежащее.", ky: "«Куштар» — ээ." },
  },
  {
    id: "g-read8-e", type: "number_input", subject: "reading", topic: "read8", grade: 8,
    difficulty: 3, free: false,
    prompt: { ru: "Сколько слов в предложении: «Наступила холодная зима»?", ky: "«Суук кыш келди» сүйлөмүндө канча сөз?" },
    answer: 3,
    explanation: { ru: "Слова: три.", ky: "Сөздөр: үчөө." },
  },
  {
    id: "g-read9-d", type: "single_choice", subject: "reading", topic: "read9", grade: 9,
    difficulty: 3, free: true,
    prompt: { ru: "Найди антоним к слову «трудный»", ky: "«Татаал» сөзүнө антонимди тап" },
    options: [{ ru: "лёгкий", ky: "жеңил" }, { ru: "тяжёлый", ky: "оор" }, { ru: "длинный", ky: "узун" }],
    correctIndex: 0,
    explanation: { ru: "«Лёгкий» — противоположность «трудного».", ky: "«Жеңил» — «татаал» дегендин карама-каршысы." },
  },
  {
    id: "g-read9-e", type: "single_choice", subject: "reading", topic: "read9", grade: 9,
    difficulty: 3, free: false,
    prompt: { ru: "Найди синоним к слову «известный»", ky: "«Белгилүү» сөзүнө синонимди тап" },
    options: [{ ru: "знаменитый", ky: "атактуу" }, { ru: "тайный", ky: "жашыруун" }, { ru: "новый", ky: "жаңы" }],
    correctIndex: 0,
    explanation: { ru: "«Знаменитый» близко по значению к «известный».", ky: "«Атактуу» — «белгилүү» менен маанилеш." },
  },
  {
    id: "g-read10-d", type: "single_choice", subject: "reading", topic: "read10", grade: 10,
    difficulty: 3, free: true,
    prompt: { ru: "Найди прилагательное", ky: "Сын атоочту тап" },
    options: [{ ru: "быстро", ky: "тез" }, { ru: "красивый", ky: "кооз" }, { ru: "бежать", ky: "чуркоо" }],
    correctIndex: 1,
    explanation: { ru: "«Красивый» — признак предмета.", ky: "«Кооз» — заттын белгиси." },
  },
  {
    id: "g-read10-e", type: "single_choice", subject: "reading", topic: "read10", grade: 10,
    difficulty: 3, free: false,
    prompt: { ru: "Каков тип предложения «Как красиво!» по интонации?", ky: "«Кандай кооз!» сүйлөмү интонация боюнча кандай?" },
    options: [{ ru: "восклицательное", ky: "илептүү" }, { ru: "вопросительное", ky: "суроолуу" }, { ru: "повествовательное", ky: "жай" }],
    correctIndex: 0,
    explanation: { ru: "Предложение с сильным чувством — восклицательное.", ky: "Күчтүү сезим менен айтылган сүйлөм — илептүү." },
  },
  {
    id: "g-read11-d", type: "single_choice", subject: "reading", topic: "read11", grade: 11,
    difficulty: 3, free: true,
    prompt: { ru: "Какое слово лишнее по смыслу?", ky: "Кайсы сөз мааниси боюнча ашык?" },
    options: [{ ru: "море", ky: "деңиз" }, { ru: "река", ky: "дарыя" }, { ru: "озеро", ky: "көл" }, { ru: "гора", ky: "тоо" }],
    correctIndex: 3,
    explanation: { ru: "«Гора» — не водоём, остальные — вода.", ky: "«Тоо» — суу эмес, калгандары — суу." },
  },
  {
    id: "g-read11-e", type: "single_choice", subject: "reading", topic: "read11", grade: 11,
    difficulty: 3, free: false,
    prompt: { ru: "Найди антоним к слову «богатый»", ky: "«Бай» сөзүнө антонимди тап" },
    options: [{ ru: "бедный", ky: "кедей" }, { ru: "добрый", ky: "боорукер" }, { ru: "сильный", ky: "күчтүү" }],
    correctIndex: 0,
    explanation: { ru: "«Бедный» — противоположность «богатого».", ky: "«Кедей» — «бай» дегендин карама-каршысы." },
  },
];

// ── МАТЕМАТИКА (геометрия и уравнения, вручную) ────────
const MATH: Task[] = [
  // 7 класс — периметр и площадь
  {
    id: "g-m7-geo-a", type: "number_input", subject: "math", topic: "m7-geo", grade: 7,
    difficulty: 3, free: true,
    prompt: { ru: "Площадь прямоугольника со сторонами 4 и 6?", ky: "Тараптары 4 жана 6 болгон тик бурчтуктун аянты?" },
    answer: 24,
    explanation: { ru: "Площадь = длина × ширина = 4 × 6 = 24.", ky: "Аянт = узундук × туурасы = 4 × 6 = 24." },
  },
  {
    id: "g-m7-geo-b", type: "number_input", subject: "math", topic: "m7-geo", grade: 7,
    difficulty: 3, free: true,
    prompt: { ru: "Периметр квадрата со стороной 5?", ky: "Тарабы 5 болгон чарчынын периметри?" },
    answer: 20,
    explanation: { ru: "Периметр = 4 × сторона = 4 × 5 = 20.", ky: "Периметр = 4 × тарап = 4 × 5 = 20." },
  },
  {
    id: "g-m7-geo-c", type: "number_input", subject: "math", topic: "m7-geo", grade: 7,
    difficulty: 3, free: false,
    prompt: { ru: "Площадь прямоугольного треугольника с катетами 6 и 8?", ky: "Катеттери 6 жана 8 болгон тик бурчтуу үч бурчтуктун аянты?" },
    answer: 24,
    explanation: { ru: "Площадь = ½ × 6 × 8 = 24.", ky: "Аянт = ½ × 6 × 8 = 24." },
  },
  // 8 класс — теорема Пифагора
  {
    id: "g-m8-geo-a", type: "number_input", subject: "math", topic: "m8-geo", grade: 8,
    difficulty: 3, free: true,
    prompt: { ru: "Гипотенуза прямоугольного треугольника с катетами 3 и 4?", ky: "Катеттери 3 жана 4 болгон тик бурчтуу үч бурчтуктун гипотенузасы?" },
    answer: 5,
    explanation: { ru: "√(3² + 4²) = √25 = 5.", ky: "√(3² + 4²) = √25 = 5." },
  },
  {
    id: "g-m8-geo-b", type: "number_input", subject: "math", topic: "m8-geo", grade: 8,
    difficulty: 3, free: true,
    prompt: { ru: "Гипотенуза при катетах 6 и 8?", ky: "Катеттери 6 жана 8 болгондо гипотенуза?" },
    answer: 10,
    explanation: { ru: "√(6² + 8²) = √100 = 10.", ky: "√(6² + 8²) = √100 = 10." },
  },
  {
    id: "g-m8-geo-c", type: "number_input", subject: "math", topic: "m8-geo", grade: 8,
    difficulty: 3, free: false,
    prompt: { ru: "Катет, если гипотенуза 13, а другой катет 5?", ky: "Гипотенуза 13, экинчи катет 5 болсо, катет канча?" },
    answer: 12,
    explanation: { ru: "√(13² − 5²) = √144 = 12.", ky: "√(13² − 5²) = √144 = 12." },
  },
  // 9 класс — площади фигур
  {
    id: "g-m9-geo-a", type: "number_input", subject: "math", topic: "m9-geo", grade: 9,
    difficulty: 3, free: true,
    prompt: { ru: "Площадь квадрата со стороной 9?", ky: "Тарабы 9 болгон чарчынын аянты?" },
    answer: 81,
    explanation: { ru: "Площадь = 9² = 81.", ky: "Аянт = 9² = 81." },
  },
  {
    id: "g-m9-geo-b", type: "number_input", subject: "math", topic: "m9-geo", grade: 9,
    difficulty: 3, free: true,
    prompt: { ru: "Площадь треугольника с основанием 10 и высотой 6?", ky: "Негизи 10, бийиктиги 6 болгон үч бурчтуктун аянты?" },
    answer: 30,
    explanation: { ru: "Площадь = ½ × основание × высота = ½ × 10 × 6 = 30.", ky: "Аянт = ½ × негиз × бийиктик = ½ × 10 × 6 = 30." },
  },
  {
    id: "g-m9-geo-c", type: "number_input", subject: "math", topic: "m9-geo", grade: 9,
    difficulty: 3, free: false,
    prompt: { ru: "Площадь параллелограмма с основанием 7 и высотой 4?", ky: "Негизи 7, бийиктиги 4 болгон параллелограммдын аянты?" },
    answer: 28,
    explanation: { ru: "Площадь = основание × высота = 7 × 4 = 28.", ky: "Аянт = негиз × бийиктик = 7 × 4 = 28." },
  },
  // 10 класс — квадратные уравнения
  {
    id: "g-m10-eq-a", type: "number_input", subject: "math", topic: "m10-eq", grade: 10,
    difficulty: 3, free: true,
    prompt: { ru: "x² = 49. Положительный корень?", ky: "x² = 49. Оң тамыры?" },
    answer: 7,
    explanation: { ru: "x = √49 = 7.", ky: "x = √49 = 7." },
  },
  {
    id: "g-m10-eq-b", type: "number_input", subject: "math", topic: "m10-eq", grade: 10,
    difficulty: 3, free: true,
    prompt: { ru: "x² − 5x + 6 = 0. Больший корень?", ky: "x² − 5x + 6 = 0. Чоң тамыры?" },
    answer: 3,
    explanation: { ru: "Корни 2 и 3 (2 × 3 = 6, 2 + 3 = 5). Больший — 3.", ky: "Тамырлар 2 жана 3 (2 × 3 = 6, 2 + 3 = 5). Чоңу — 3." },
  },
  {
    id: "g-m10-eq-c", type: "number_input", subject: "math", topic: "m10-eq", grade: 10,
    difficulty: 3, free: false,
    prompt: { ru: "x² − 7x + 12 = 0. Меньший корень?", ky: "x² − 7x + 12 = 0. Кичине тамыры?" },
    answer: 3,
    explanation: { ru: "Корни 3 и 4 (3 × 4 = 12, 3 + 4 = 7). Меньший — 3.", ky: "Тамырлар 3 жана 4 (3 × 4 = 12, 3 + 4 = 7). Кичинеси — 3." },
  },
  // 11 класс — объёмы тел
  {
    id: "g-m11-geo-a", type: "number_input", subject: "math", topic: "m11-geo", grade: 11,
    difficulty: 3, free: true,
    prompt: { ru: "Объём куба с ребром 3?", ky: "Кыры 3 болгон кубдун көлөмү?" },
    answer: 27,
    explanation: { ru: "Объём = 3³ = 27.", ky: "Көлөм = 3³ = 27." },
  },
  {
    id: "g-m11-geo-b", type: "number_input", subject: "math", topic: "m11-geo", grade: 11,
    difficulty: 3, free: true,
    prompt: { ru: "Объём коробки 2 × 3 × 4?", ky: "2 × 3 × 4 кутучанын көлөмү?" },
    answer: 24,
    explanation: { ru: "Объём = 2 × 3 × 4 = 24.", ky: "Көлөм = 2 × 3 × 4 = 24." },
  },
  {
    id: "g-m11-geo-c", type: "number_input", subject: "math", topic: "m11-geo", grade: 11,
    difficulty: 3, free: false,
    prompt: { ru: "Объём куба с ребром 5?", ky: "Кыры 5 болгон кубдун көлөмү?" },
    answer: 125,
    explanation: { ru: "Объём = 5³ = 125.", ky: "Көлөм = 5³ = 125." },
  },
  // ── Дополнительные задания (второй проход) ──
  {
    id: "g-m7-geo-d", type: "number_input", subject: "math", topic: "m7-geo", grade: 7,
    difficulty: 3, free: false,
    prompt: { ru: "Периметр прямоугольника со сторонами 3 и 7?", ky: "Тараптары 3 жана 7 болгон тик бурчтуктун периметри?" },
    answer: 20,
    explanation: { ru: "Периметр = 2 × (3 + 7) = 20.", ky: "Периметр = 2 × (3 + 7) = 20." },
  },
  {
    id: "g-m7-geo-e", type: "number_input", subject: "math", topic: "m7-geo", grade: 7,
    difficulty: 3, free: false,
    prompt: { ru: "Площадь квадрата со стороной 8?", ky: "Тарабы 8 болгон чарчынын аянты?" },
    answer: 64,
    explanation: { ru: "Площадь = 8 × 8 = 64.", ky: "Аянт = 8 × 8 = 64." },
  },
  {
    id: "g-m8-geo-d", type: "number_input", subject: "math", topic: "m8-geo", grade: 8,
    difficulty: 3, free: false,
    prompt: { ru: "Гипотенуза при катетах 5 и 12?", ky: "Катеттери 5 жана 12 болгондо гипотенуза?" },
    answer: 13,
    explanation: { ru: "√(5² + 12²) = √169 = 13.", ky: "√(5² + 12²) = √169 = 13." },
  },
  {
    id: "g-m8-geo-e", type: "number_input", subject: "math", topic: "m8-geo", grade: 8,
    difficulty: 3, free: false,
    prompt: { ru: "Гипотенуза при катетах 8 и 15?", ky: "Катеттери 8 жана 15 болгондо гипотенуза?" },
    answer: 17,
    explanation: { ru: "√(8² + 15²) = √289 = 17.", ky: "√(8² + 15²) = √289 = 17." },
  },
  {
    id: "g-m9-geo-d", type: "number_input", subject: "math", topic: "m9-geo", grade: 9,
    difficulty: 3, free: false,
    prompt: { ru: "Площадь прямоугольника 12 × 5?", ky: "12 × 5 тик бурчтуктун аянты?" },
    answer: 60,
    explanation: { ru: "Площадь = 12 × 5 = 60.", ky: "Аянт = 12 × 5 = 60." },
  },
  {
    id: "g-m9-geo-e", type: "number_input", subject: "math", topic: "m9-geo", grade: 9,
    difficulty: 3, free: false,
    prompt: { ru: "Площадь треугольника с основанием 8 и высотой 5?", ky: "Негизи 8, бийиктиги 5 болгон үч бурчтуктун аянты?" },
    answer: 20,
    explanation: { ru: "Площадь = ½ × 8 × 5 = 20.", ky: "Аянт = ½ × 8 × 5 = 20." },
  },
  {
    id: "g-m10-eq-d", type: "number_input", subject: "math", topic: "m10-eq", grade: 10,
    difficulty: 3, free: false,
    prompt: { ru: "x² = 64. Положительный корень?", ky: "x² = 64. Оң тамыры?" },
    answer: 8,
    explanation: { ru: "x = √64 = 8.", ky: "x = √64 = 8." },
  },
  {
    id: "g-m10-eq-e", type: "number_input", subject: "math", topic: "m10-eq", grade: 10,
    difficulty: 3, free: false,
    prompt: { ru: "x² − 8x + 15 = 0. Больший корень?", ky: "x² − 8x + 15 = 0. Чоң тамыры?" },
    answer: 5,
    explanation: { ru: "Корни 3 и 5 (3 × 5 = 15, 3 + 5 = 8). Больший — 5.", ky: "Тамырлар 3 жана 5 (3 × 5 = 15, 3 + 5 = 8). Чоңу — 5." },
  },
  {
    id: "g-m11-geo-d", type: "number_input", subject: "math", topic: "m11-geo", grade: 11,
    difficulty: 3, free: false,
    prompt: { ru: "Объём куба с ребром 4?", ky: "Кыры 4 болгон кубдун көлөмү?" },
    answer: 64,
    explanation: { ru: "Объём = 4³ = 64.", ky: "Көлөм = 4³ = 64." },
  },
  {
    id: "g-m11-geo-e", type: "number_input", subject: "math", topic: "m11-geo", grade: 11,
    difficulty: 3, free: false,
    prompt: { ru: "Объём коробки 3 × 3 × 5?", ky: "3 × 3 × 5 кутучанын көлөмү?" },
    answer: 45,
    explanation: { ru: "Объём = 3 × 3 × 5 = 45.", ky: "Көлөм = 3 × 3 × 5 = 45." },
  },
];

// ── ОКРУЖАЮЩИЙ МИР ─────────────────────────────────────
const WORLD: Task[] = [
  // 5 класс — природа и Земля
  {
    id: "g-world5-a", type: "number_input", subject: "world", topic: "world5", grade: 5,
    difficulty: 2, free: true,
    prompt: { ru: "Сколько планет в Солнечной системе?", ky: "Күн системасында канча планета бар?" },
    answer: 8,
    explanation: { ru: "Восемь планет — от Меркурия до Нептуна.", ky: "Сегиз планета — Меркурийден Нептунга чейин." },
  },
  {
    id: "g-world5-b", type: "single_choice", subject: "world", topic: "world5", grade: 5,
    difficulty: 2, free: true,
    prompt: { ru: "Какая планета самая большая?", ky: "Кайсы планета эң чоң?" },
    options: [{ ru: "Земля", ky: "Жер" }, { ru: "Юпитер", ky: "Юпитер" }, { ru: "Марс", ky: "Марс" }],
    correctIndex: 1,
    explanation: { ru: "Юпитер — самая большая планета Солнечной системы.", ky: "Юпитер — Күн системасынын эң чоң планетасы." },
  },
  {
    id: "g-world5-c", type: "single_choice", subject: "world", topic: "world5", grade: 5,
    difficulty: 2, free: false,
    prompt: { ru: "Какой газ выделяют растения на свету?", ky: "Өсүмдүктөр жарыкта кайсы газды бөлүп чыгарат?" },
    options: [{ ru: "Кислород", ky: "Кычкылтек" }, { ru: "Углекислый газ", ky: "Көмүр кычкыл газы" }, { ru: "Азот", ky: "Азот" }],
    correctIndex: 0,
    explanation: { ru: "При фотосинтезе растения выделяют кислород.", ky: "Фотосинтезде өсүмдүктөр кычкылтек бөлүп чыгарат." },
  },
  // 6 класс — география
  {
    id: "g-world6-a", type: "number_input", subject: "world", topic: "world6", grade: 6,
    difficulty: 2, free: true,
    prompt: { ru: "Сколько материков на Земле?", ky: "Жерде канча материк бар?" },
    answer: 6,
    explanation: { ru: "Шесть материков: Евразия, Африка, Северная и Южная Америка, Австралия, Антарктида.", ky: "Алты материк: Евразия, Африка, Түндүк жана Түштүк Америка, Австралия, Антарктида." },
  },
  {
    id: "g-world6-b", type: "single_choice", subject: "world", topic: "world6", grade: 6,
    difficulty: 2, free: true,
    prompt: { ru: "Какой океан самый большой?", ky: "Кайсы океан эң чоң?" },
    options: [{ ru: "Тихий", ky: "Тынч" }, { ru: "Атлантический", ky: "Атлантика" }, { ru: "Индийский", ky: "Инди" }],
    correctIndex: 0,
    explanation: { ru: "Тихий океан — самый большой на планете.", ky: "Тынч океан — планетадагы эң чоңу." },
  },
  {
    id: "g-world6-c", type: "single_choice", subject: "world", topic: "world6", grade: 6,
    difficulty: 2, free: false,
    prompt: { ru: "Какое озеро самое глубокое в мире?", ky: "Дүйнөдөгү эң терең көл кайсы?" },
    options: [{ ru: "Байкал", ky: "Байкал" }, { ru: "Иссык-Куль", ky: "Ысык-Көл" }, { ru: "Балхаш", ky: "Балкаш" }],
    correctIndex: 0,
    explanation: { ru: "Байкал — самое глубокое озеро на Земле.", ky: "Байкал — Жердеги эң терең көл." },
  },
  // 7 класс — человек и биология
  {
    id: "g-world7-a", type: "number_input", subject: "world", topic: "world7", grade: 7,
    difficulty: 3, free: true,
    prompt: { ru: "Сколько костей в теле взрослого человека?", ky: "Чоң кишинин денесинде канча сөөк бар?" },
    answer: 206,
    explanation: { ru: "У взрослого человека 206 костей.", ky: "Чоң кишиде 206 сөөк бар." },
  },
  {
    id: "g-world7-b", type: "single_choice", subject: "world", topic: "world7", grade: 7,
    difficulty: 3, free: true,
    prompt: { ru: "Какой орган перекачивает кровь?", ky: "Кайсы орган канды айдайт?" },
    options: [{ ru: "Сердце", ky: "Жүрөк" }, { ru: "Лёгкие", ky: "Өпкө" }, { ru: "Печень", ky: "Боор" }],
    correctIndex: 0,
    explanation: { ru: "Сердце работает как насос и перекачивает кровь.", ky: "Жүрөк насос сыяктуу иштеп, канды айдайт." },
  },
  {
    id: "g-world7-c", type: "number_input", subject: "world", topic: "world7", grade: 7,
    difficulty: 3, free: false,
    prompt: { ru: "Сколько камер у сердца человека?", ky: "Адамдын жүрөгүндө канча бөлүм бар?" },
    answer: 4,
    explanation: { ru: "Четыре камеры: два предсердия и два желудочка.", ky: "Төрт бөлүм: эки жүрөкчө жана эки карынча." },
  },
  // 8 класс — физика и химия
  {
    id: "g-world8-a", type: "single_choice", subject: "world", topic: "world8", grade: 8,
    difficulty: 3, free: true,
    prompt: { ru: "Какая химическая формула у воды?", ky: "Суунун химиялык формуласы кандай?" },
    options: [{ ru: "H₂O", ky: "H₂O" }, { ru: "CO₂", ky: "CO₂" }, { ru: "O₂", ky: "O₂" }],
    correctIndex: 0,
    explanation: { ru: "Вода — H₂O: два атома водорода и один кислорода.", ky: "Суу — H₂O: эки суутек жана бир кычкылтек атому." },
  },
  {
    id: "g-world8-b", type: "number_input", subject: "world", topic: "world8", grade: 8,
    difficulty: 3, free: true,
    prompt: { ru: "При какой температуре кипит вода (°C)?", ky: "Суу канча температурада кайнайт (°C)?" },
    answer: 100,
    explanation: { ru: "При нормальном давлении вода кипит при 100 °C.", ky: "Кадимки басымда суу 100 °C'та кайнайт." },
  },
  {
    id: "g-world8-c", type: "single_choice", subject: "world", topic: "world8", grade: 8,
    difficulty: 3, free: false,
    prompt: { ru: "Какой газ нужен человеку для дыхания?", ky: "Адамга дем алуу үчүн кайсы газ керек?" },
    options: [{ ru: "Кислород", ky: "Кычкылтек" }, { ru: "Азот", ky: "Азот" }, { ru: "Водород", ky: "Суутек" }],
    correctIndex: 0,
    explanation: { ru: "Для дыхания нужен кислород.", ky: "Дем алуу үчүн кычкылтек керек." },
  },
  // 9 класс — химия и физика
  {
    id: "g-world9-a", type: "single_choice", subject: "world", topic: "world9", grade: 9,
    difficulty: 3, free: true,
    prompt: { ru: "Каким символом обозначают кислород?", ky: "Кычкылтек кайсы символ менен белгиленет?" },
    options: [{ ru: "O", ky: "O" }, { ru: "H", ky: "H" }, { ru: "C", ky: "C" }],
    correctIndex: 0,
    explanation: { ru: "Кислород обозначают символом O.", ky: "Кычкылтек O символу менен белгиленет." },
  },
  {
    id: "g-world9-b", type: "single_choice", subject: "world", topic: "world9", grade: 9,
    difficulty: 3, free: true,
    prompt: { ru: "В каких единицах измеряют силу?", ky: "Күч кайсы бирдикте өлчөнөт?" },
    options: [{ ru: "Ньютон", ky: "Ньютон" }, { ru: "Джоуль", ky: "Джоуль" }, { ru: "Ватт", ky: "Ватт" }],
    correctIndex: 0,
    explanation: { ru: "Силу измеряют в ньютонах (Н).", ky: "Күч ньютон менен өлчөнөт (Н)." },
  },
  {
    id: "g-world9-c", type: "number_input", subject: "world", topic: "world9", grade: 9,
    difficulty: 3, free: false,
    prompt: { ru: "При какой температуре замерзает вода (°C)?", ky: "Суу канча температурада катат (°C)?" },
    answer: 0,
    explanation: { ru: "Вода замерзает при 0 °C.", ky: "Суу 0 °C'та катат." },
  },
  // 10 класс — наука о природе
  {
    id: "g-world10-a", type: "single_choice", subject: "world", topic: "world10", grade: 10,
    difficulty: 3, free: true,
    prompt: { ru: "Какая планета ближе всех к Солнцу?", ky: "Кайсы планета Күнгө эң жакын?" },
    options: [{ ru: "Меркурий", ky: "Меркурий" }, { ru: "Венера", ky: "Венера" }, { ru: "Земля", ky: "Жер" }],
    correctIndex: 0,
    explanation: { ru: "Меркурий — ближайшая к Солнцу планета.", ky: "Меркурий — Күнгө эң жакын планета." },
  },
  {
    id: "g-world10-b", type: "single_choice", subject: "world", topic: "world10", grade: 10,
    difficulty: 3, free: true,
    prompt: { ru: "В каких единицах измеряют энергию?", ky: "Энергия кайсы бирдикте өлчөнөт?" },
    options: [{ ru: "Джоуль", ky: "Джоуль" }, { ru: "Ньютон", ky: "Ньютон" }, { ru: "Ампер", ky: "Ампер" }],
    correctIndex: 0,
    explanation: { ru: "Энергию измеряют в джоулях (Дж).", ky: "Энергия джоуль менен өлчөнөт (Дж)." },
  },
  // 11 класс — наука и космос
  {
    id: "g-world11-a", type: "single_choice", subject: "world", topic: "world11", grade: 11,
    difficulty: 3, free: true,
    prompt: { ru: "Чему примерно равна скорость света?", ky: "Жарыктын ылдамдыгы болжол менен канчага барабар?" },
    options: [{ ru: "300 000 км/с", ky: "300 000 км/с" }, { ru: "3 000 км/с", ky: "3 000 км/с" }, { ru: "30 км/с", ky: "30 км/с" }],
    correctIndex: 0,
    explanation: { ru: "Скорость света — около 300 000 км/с.", ky: "Жарыктын ылдамдыгы — болжол менен 300 000 км/с." },
  },
  {
    id: "g-world11-b", type: "single_choice", subject: "world", topic: "world11", grade: 11,
    difficulty: 3, free: true,
    prompt: { ru: "Каким символом обозначают золото?", ky: "Алтын кайсы символ менен белгиленет?" },
    options: [{ ru: "Au", ky: "Au" }, { ru: "Ag", ky: "Ag" }, { ru: "Fe", ky: "Fe" }],
    correctIndex: 0,
    explanation: { ru: "Золото обозначают символом Au (от лат. aurum).", ky: "Алтын Au символу менен белгиленет (лат. aurum)." },
  },
  // ── Окружающий мир 5–11: дополнительные задания (второй проход) ──
  {
    id: "g-world5-d", type: "number_input", subject: "world", topic: "world5", grade: 5,
    difficulty: 2, free: true,
    prompt: { ru: "Сколько ног у паука?", ky: "Жөргөмүштүн канча буту бар?" },
    answer: 8,
    explanation: { ru: "У паука восемь ног.", ky: "Жөргөмүштүн сегиз буту бар." },
  },
  {
    id: "g-world5-e", type: "single_choice", subject: "world", topic: "world5", grade: 5,
    difficulty: 2, free: false,
    prompt: { ru: "Что из этого растёт на дереве?", ky: "Булардын кайсынысы даракта өсөт?" },
    options: [{ ru: "листья", ky: "жалбырактар" }, { ru: "камни", ky: "таштар" }, { ru: "стекло", ky: "айнек" }],
    correctIndex: 0,
    explanation: { ru: "На деревьях растут листья.", ky: "Дарактарда жалбырактар өсөт." },
  },
  {
    id: "g-world6-d", type: "single_choice", subject: "world", topic: "world6", grade: 6,
    difficulty: 2, free: true,
    prompt: { ru: "Самая высокая гора в мире?", ky: "Дүйнөдөгү эң бийик тоо?" },
    options: [{ ru: "Эверест", ky: "Эверест" }, { ru: "Эльбрус", ky: "Эльбрус" }, { ru: "Казбек", ky: "Казбек" }],
    correctIndex: 0,
    explanation: { ru: "Эверест — самая высокая гора на Земле.", ky: "Эверест — Жердеги эң бийик тоо." },
  },
  {
    id: "g-world6-e", type: "number_input", subject: "world", topic: "world6", grade: 6,
    difficulty: 2, free: false,
    prompt: { ru: "Сколько основных сторон света?", ky: "Дүйнөнүн канча негизги тарабы бар?" },
    answer: 4,
    explanation: { ru: "Четыре: север, юг, запад, восток.", ky: "Төртөө: түндүк, түштүк, батыш, чыгыш." },
  },
  {
    id: "g-world7-d", type: "number_input", subject: "world", topic: "world7", grade: 7,
    difficulty: 3, free: true,
    prompt: { ru: "Сколько лёгких у человека?", ky: "Адамда канча өпкө бар?" },
    answer: 2,
    explanation: { ru: "У человека два лёгких.", ky: "Адамда эки өпкө бар." },
  },
  {
    id: "g-world7-e", type: "single_choice", subject: "world", topic: "world7", grade: 7,
    difficulty: 3, free: false,
    prompt: { ru: "Каким органом человек видит?", ky: "Адам кайсы органы менен көрөт?" },
    options: [{ ru: "глаз", ky: "көз" }, { ru: "ухо", ky: "кулак" }, { ru: "нос", ky: "мурун" }],
    correctIndex: 0,
    explanation: { ru: "Мы видим глазами.", ky: "Биз көз менен көрөбүз." },
  },
  {
    id: "g-world8-d", type: "single_choice", subject: "world", topic: "world8", grade: 8,
    difficulty: 3, free: true,
    prompt: { ru: "Что притягивает предметы к Земле?", ky: "Буюмдарды Жерге эмне тартат?" },
    options: [{ ru: "гравитация", ky: "гравитация" }, { ru: "ветер", ky: "шамал" }, { ru: "свет", ky: "жарык" }],
    correctIndex: 0,
    explanation: { ru: "Предметы притягивает сила тяжести — гравитация.", ky: "Буюмдарды тартылуу күчү — гравитация тартат." },
  },
  {
    id: "g-world8-e", type: "number_input", subject: "world", topic: "world8", grade: 8,
    difficulty: 3, free: false,
    prompt: { ru: "Сколько атомов водорода в молекуле воды H₂O?", ky: "Суунун H₂O молекуласында канча суутек атому бар?" },
    answer: 2,
    explanation: { ru: "В H₂O два атома водорода.", ky: "H₂O'до эки суутек атому бар." },
  },
  {
    id: "g-world9-d", type: "single_choice", subject: "world", topic: "world9", grade: 9,
    difficulty: 3, free: true,
    prompt: { ru: "Каким символом обозначают водород?", ky: "Суутек кайсы символ менен белгиленет?" },
    options: [{ ru: "H", ky: "H" }, { ru: "O", ky: "O" }, { ru: "N", ky: "N" }],
    correctIndex: 0,
    explanation: { ru: "Водород обозначают символом H.", ky: "Суутек H символу менен белгиленет." },
  },
  {
    id: "g-world9-e", type: "single_choice", subject: "world", topic: "world9", grade: 9,
    difficulty: 3, free: false,
    prompt: { ru: "В каких единицах измеряют силу электрического тока?", ky: "Электр тогунун күчү кайсы бирдикте өлчөнөт?" },
    options: [{ ru: "Ампер", ky: "Ампер" }, { ru: "Ватт", ky: "Ватт" }, { ru: "Джоуль", ky: "Джоуль" }],
    correctIndex: 0,
    explanation: { ru: "Силу тока измеряют в амперах (А).", ky: "Ток күчү ампер менен өлчөнөт (А)." },
  },
  {
    id: "g-world10-d", type: "number_input", subject: "world", topic: "world10", grade: 10,
    difficulty: 3, free: true,
    prompt: { ru: "Сколько естественных спутников у Земли?", ky: "Жердин канча табигый жандоочу бар?" },
    answer: 1,
    explanation: { ru: "Один — Луна.", ky: "Бирөө — Ай." },
  },
  {
    id: "g-world10-e", type: "single_choice", subject: "world", topic: "world10", grade: 10,
    difficulty: 3, free: false,
    prompt: { ru: "Какую планету называют «красной»?", ky: "Кайсы планетаны «кызыл» деп аташат?" },
    options: [{ ru: "Марс", ky: "Марс" }, { ru: "Венера", ky: "Венера" }, { ru: "Юпитер", ky: "Юпитер" }],
    correctIndex: 0,
    explanation: { ru: "Марс называют красной планетой из-за цвета поверхности.", ky: "Марсты бетинин түсүнөн улам кызыл планета деп аташат." },
  },
  {
    id: "g-world11-c", type: "single_choice", subject: "world", topic: "world11", grade: 11,
    difficulty: 3, free: false,
    prompt: { ru: "Каким символом обозначают железо?", ky: "Темир кайсы символ менен белгиленет?" },
    options: [{ ru: "Fe", ky: "Fe" }, { ru: "Au", ky: "Au" }, { ru: "Ag", ky: "Ag" }],
    correctIndex: 0,
    explanation: { ru: "Железо обозначают символом Fe (от лат. ferrum).", ky: "Темир Fe символу менен белгиленет (лат. ferrum)." },
  },
  {
    id: "g-world11-d", type: "single_choice", subject: "world", topic: "world11", grade: 11,
    difficulty: 3, free: false,
    prompt: { ru: "Какая звезда ближе всех к Земле?", ky: "Жерге эң жакын жылдыз кайсы?" },
    options: [{ ru: "Солнце", ky: "Күн" }, { ru: "Сириус", ky: "Сириус" }, { ru: "Полярная", ky: "Полярдык" }],
    correctIndex: 0,
    explanation: { ru: "Солнце — ближайшая к Земле звезда.", ky: "Күн — Жерге эң жакын жылдыз." },
  },
];

// Окружающий мир для младших классов (1–4) — простые факты о природе.
const WORLD_LOWER: Task[] = [
  // 1 класс — природа вокруг
  {
    id: "g-world1-a", type: "number_input", subject: "world", topic: "world1", grade: 1,
    difficulty: 1, free: true,
    prompt: { ru: "Сколько лап у собаки?", ky: "Иттин канча буту бар?" },
    answer: 4,
    explanation: { ru: "У собаки четыре лапы.", ky: "Иттин төрт буту бар." },
  },
  {
    id: "g-world1-b", type: "single_choice", subject: "world", topic: "world1", grade: 1,
    difficulty: 1, free: true,
    prompt: { ru: "Кто из них птица?", ky: "Булардын кайсынысы куш?" },
    options: [{ ru: "кошка", ky: "мышык" }, { ru: "воробей", ky: "таранчы" }, { ru: "рыба", ky: "балык" }],
    correctIndex: 1,
    explanation: { ru: "Воробей — птица, он умеет летать.", ky: "Таранчы — куш, ал уча алат." },
  },
  {
    id: "g-world1-c", type: "single_choice", subject: "world", topic: "world1", grade: 1,
    difficulty: 1, free: false,
    prompt: { ru: "Что нужно растению, чтобы расти?", ky: "Өсүмдүккө өсүү үчүн эмне керек?" },
    options: [{ ru: "свет", ky: "жарык" }, { ru: "темнота", ky: "караңгы" }, { ru: "шум", ky: "ызы-чуу" }],
    correctIndex: 0,
    explanation: { ru: "Растениям нужен свет солнца.", ky: "Өсүмдүктөргө күндүн жарыгы керек." },
  },
  // 2 класс — времена года
  {
    id: "g-world2-a", type: "number_input", subject: "world", topic: "world2", grade: 2,
    difficulty: 1, free: true,
    prompt: { ru: "Сколько всего времён года?", ky: "Жылда канча мезгил бар?" },
    answer: 4,
    explanation: { ru: "Четыре: зима, весна, лето, осень.", ky: "Төртөө: кыш, жаз, жай, күз." },
  },
  {
    id: "g-world2-b", type: "single_choice", subject: "world", topic: "world2", grade: 2,
    difficulty: 1, free: true,
    prompt: { ru: "Когда идёт снег?", ky: "Кар качан жаайт?" },
    options: [{ ru: "зимой", ky: "кышында" }, { ru: "летом", ky: "жайында" }],
    correctIndex: 0,
    explanation: { ru: "Снег идёт зимой, когда холодно.", ky: "Кар кышында, суук болгондо жаайт." },
  },
  {
    id: "g-world2-c", type: "single_choice", subject: "world", topic: "world2", grade: 2,
    difficulty: 1, free: false,
    prompt: { ru: "Что даёт нам корова?", ky: "Уй бизге эмне берет?" },
    options: [{ ru: "молоко", ky: "сүт" }, { ru: "мёд", ky: "бал" }, { ru: "шерсть", ky: "жүн" }],
    correctIndex: 0,
    explanation: { ru: "Корова даёт молоко.", ky: "Уй сүт берет." },
  },
  // 3 класс — живая природа
  {
    id: "g-world3-a", type: "number_input", subject: "world", topic: "world3", grade: 3,
    difficulty: 2, free: true,
    prompt: { ru: "Сколько лапок у насекомого?", ky: "Курт-кумурсканын канча буту бар?" },
    answer: 6,
    explanation: { ru: "У насекомых шесть лапок.", ky: "Курт-кумурсканын алты буту бар." },
  },
  {
    id: "g-world3-b", type: "single_choice", subject: "world", topic: "world3", grade: 3,
    difficulty: 2, free: true,
    prompt: { ru: "Кто дышит под водой жабрами?", ky: "Суу астында бранхий менен ким дем алат?" },
    options: [{ ru: "рыба", ky: "балык" }, { ru: "кошка", ky: "мышык" }, { ru: "птица", ky: "куш" }],
    correctIndex: 0,
    explanation: { ru: "Рыбы дышат жабрами под водой.", ky: "Балыктар суу астында бранхий менен дем алат." },
  },
  {
    id: "g-world3-c", type: "single_choice", subject: "world", topic: "world3", grade: 3,
    difficulty: 2, free: false,
    prompt: { ru: "Что делают пчёлы?", ky: "Аарылар эмне жасайт?" },
    options: [{ ru: "мёд", ky: "бал" }, { ru: "молоко", ky: "сүт" }, { ru: "шерсть", ky: "жүн" }],
    correctIndex: 0,
    explanation: { ru: "Пчёлы делают мёд.", ky: "Аарылар бал жасайт." },
  },
  // 4 класс — планета Земля
  {
    id: "g-world4-a", type: "number_input", subject: "world", topic: "world4", grade: 4,
    difficulty: 2, free: true,
    prompt: { ru: "Сколько дней в неделе?", ky: "Бир жумада канча күн бар?" },
    answer: 7,
    explanation: { ru: "В неделе семь дней.", ky: "Бир жумада жети күн бар." },
  },
  {
    id: "g-world4-b", type: "single_choice", subject: "world", topic: "world4", grade: 4,
    difficulty: 2, free: true,
    prompt: { ru: "Что больше: Солнце или Земля?", ky: "Кайсынысы чоң: Күнбү же Жерби?" },
    options: [{ ru: "Солнце", ky: "Күн" }, { ru: "Земля", ky: "Жер" }],
    correctIndex: 0,
    explanation: { ru: "Солнце намного больше Земли.", ky: "Күн Жерден кыйла чоң." },
  },
  {
    id: "g-world4-c", type: "single_choice", subject: "world", topic: "world4", grade: 4,
    difficulty: 2, free: false,
    prompt: { ru: "Где живут пингвины?", ky: "Пингвиндер кайда жашайт?" },
    options: [{ ru: "в холодных краях", ky: "суук жерлерде" }, { ru: "в пустыне", ky: "чөлдө" }, { ru: "в джунглях", ky: "джунглиде" }],
    correctIndex: 0,
    explanation: { ru: "Пингвины живут в холодных местах, например в Антарктиде.", ky: "Пингвиндер суук жерлерде, мисалы Антарктидада жашайт." },
  },
  // ── Окружающий мир 1–4: дополнительные задания (второй проход) ──
  {
    id: "g-world1-d", type: "number_input", subject: "world", topic: "world1", grade: 1,
    difficulty: 1, free: true,
    prompt: { ru: "Сколько лап у птицы?", ky: "Куштун канча буту бар?" },
    answer: 2,
    explanation: { ru: "У птицы две лапки.", ky: "Куштун эки буту бар." },
  },
  {
    id: "g-world1-e", type: "single_choice", subject: "world", topic: "world1", grade: 1,
    difficulty: 1, free: false,
    prompt: { ru: "Кто из них живёт в воде?", ky: "Булардын кайсынысы сууда жашайт?" },
    options: [{ ru: "рыба", ky: "балык" }, { ru: "кошка", ky: "мышык" }, { ru: "собака", ky: "ит" }],
    correctIndex: 0,
    explanation: { ru: "Рыба живёт в воде.", ky: "Балык сууда жашайт." },
  },
  {
    id: "g-world2-d", type: "single_choice", subject: "world", topic: "world2", grade: 2,
    difficulty: 1, free: true,
    prompt: { ru: "Когда листья желтеют и опадают?", ky: "Жалбырактар качан саргайып түшөт?" },
    options: [{ ru: "осенью", ky: "күзүндө" }, { ru: "зимой", ky: "кышында" }, { ru: "летом", ky: "жайында" }],
    correctIndex: 0,
    explanation: { ru: "Листья желтеют осенью.", ky: "Жалбырактар күзүндө саргаят." },
  },
  {
    id: "g-world2-e", type: "single_choice", subject: "world", topic: "world2", grade: 2,
    difficulty: 1, free: false,
    prompt: { ru: "Что даёт нам курица?", ky: "Тоок бизге эмне берет?" },
    options: [{ ru: "яйца", ky: "жумуртка" }, { ru: "молоко", ky: "сүт" }, { ru: "шерсть", ky: "жүн" }],
    correctIndex: 0,
    explanation: { ru: "Курица несёт яйца.", ky: "Тоок жумуртка тууйт." },
  },
  {
    id: "g-world3-d", type: "single_choice", subject: "world", topic: "world3", grade: 3,
    difficulty: 2, free: true,
    prompt: { ru: "Кто больше: слон или мышь?", ky: "Кайсынысы чоң: пилби же чычканбы?" },
    options: [{ ru: "слон", ky: "пил" }, { ru: "мышь", ky: "чычкан" }],
    correctIndex: 0,
    explanation: { ru: "Слон намного больше мыши.", ky: "Пил чычкандан алда канча чоң." },
  },
  {
    id: "g-world3-e", type: "single_choice", subject: "world", topic: "world3", grade: 3,
    difficulty: 2, free: false,
    prompt: { ru: "Где растут грибы?", ky: "Козу карын кайда өсөт?" },
    options: [{ ru: "в лесу", ky: "токойдо" }, { ru: "в море", ky: "деңизде" }, { ru: "в небе", ky: "асманда" }],
    correctIndex: 0,
    explanation: { ru: "Грибы растут в лесу.", ky: "Козу карын токойдо өсөт." },
  },
  {
    id: "g-world4-d", type: "number_input", subject: "world", topic: "world4", grade: 4,
    difficulty: 2, free: true,
    prompt: { ru: "Сколько месяцев в году?", ky: "Жылда канча ай бар?" },
    answer: 12,
    explanation: { ru: "В году двенадцать месяцев.", ky: "Жылда он эки ай бар." },
  },
  {
    id: "g-world4-e", type: "single_choice", subject: "world", topic: "world4", grade: 4,
    difficulty: 2, free: false,
    prompt: { ru: "Что светит на небе ночью?", ky: "Түнкүсүн асманда эмне жарык берет?" },
    options: [{ ru: "луна", ky: "ай" }, { ru: "солнце", ky: "күн" }, { ru: "радуга", ky: "асан-үсөн" }],
    correctIndex: 0,
    explanation: { ru: "Ночью на небе светит луна.", ky: "Түнкүсүн асманда ай жарык берет." },
  },
];

// Догрузка «Окружающего мира» до ~10 заданий в теме (второй проход).
const WORLD_TOPUP: Task[] = [
  // world1 (1 класс)
  { id: "g-world1-f", type: "number_input", subject: "world", topic: "world1", grade: 1, difficulty: 2, free: true,
    prompt: { ru: "Сколько глаз у человека?", ky: "Адамдын канча көзү бар?" }, answer: 2,
    explanation: { ru: "У человека два глаза.", ky: "Адамдын эки көзү бар." } },
  { id: "g-world1-g", type: "single_choice", subject: "world", topic: "world1", grade: 1, difficulty: 2, free: true,
    prompt: { ru: "Кто даёт нам мёд?", ky: "Бизге балды ким берет?" },
    options: [{ ru: "пчела", ky: "аары" }, { ru: "корова", ky: "уй" }, { ru: "курица", ky: "тоок" }], correctIndex: 0,
    explanation: { ru: "Мёд дают пчёлы.", ky: "Балды аарылар берет." } },
  { id: "g-world1-h", type: "number_input", subject: "world", topic: "world1", grade: 1, difficulty: 2, free: false,
    prompt: { ru: "Сколько крыльев у бабочки?", ky: "Көпөлөктүн канча канаты бар?" }, answer: 4,
    explanation: { ru: "У бабочки четыре крыла.", ky: "Көпөлөктүн төрт канаты бар." } },
  { id: "g-world1-i", type: "single_choice", subject: "world", topic: "world1", grade: 1, difficulty: 2, free: false,
    prompt: { ru: "Кто из них умеет летать?", ky: "Булардын кайсынысы уча алат?" },
    options: [{ ru: "птица", ky: "куш" }, { ru: "рыба", ky: "балык" }, { ru: "кошка", ky: "мышык" }], correctIndex: 0,
    explanation: { ru: "Птица умеет летать.", ky: "Куш уча алат." } },

  // world2 (2 класс)
  { id: "g-world2-f", type: "single_choice", subject: "world", topic: "world2", grade: 2, difficulty: 2, free: true,
    prompt: { ru: "Какое время года самое тёплое?", ky: "Кайсы жыл мезгили эң жылуу?" },
    options: [{ ru: "лето", ky: "жай" }, { ru: "зима", ky: "кыш" }], correctIndex: 0,
    explanation: { ru: "Летом теплее всего.", ky: "Жайында эң жылуу." } },
  { id: "g-world2-g", type: "single_choice", subject: "world", topic: "world2", grade: 2, difficulty: 2, free: true,
    prompt: { ru: "Когда на деревьях распускаются листья?", ky: "Дарактарда жалбырактар качан жайылат?" },
    options: [{ ru: "весной", ky: "жазында" }, { ru: "осенью", ky: "күзүндө" }], correctIndex: 0,
    explanation: { ru: "Листья распускаются весной.", ky: "Жалбырактар жазында жайылат." } },
  { id: "g-world2-h", type: "single_choice", subject: "world", topic: "world2", grade: 2, difficulty: 2, free: false,
    prompt: { ru: "Что появляется на небе после дождя?", ky: "Жамгырдан кийин асманда эмне пайда болот?" },
    options: [{ ru: "радуга", ky: "асан-үсөн" }, { ru: "снег", ky: "кар" }], correctIndex: 0,
    explanation: { ru: "После дождя бывает радуга.", ky: "Жамгырдан кийин асан-үсөн болот." } },
  { id: "g-world2-i", type: "single_choice", subject: "world", topic: "world2", grade: 2, difficulty: 2, free: false,
    prompt: { ru: "В какое время года катаются на санках?", ky: "Кайсы мезгилде чанага түшөт?" },
    options: [{ ru: "зимой", ky: "кышында" }, { ru: "летом", ky: "жайында" }], correctIndex: 0,
    explanation: { ru: "На санках катаются зимой.", ky: "Чанага кышында түшөт." } },

  // world3 (3 класс)
  { id: "g-world3-f", type: "single_choice", subject: "world", topic: "world3", grade: 3, difficulty: 2, free: true,
    prompt: { ru: "Самое большое животное на суше?", ky: "Кургактыктагы эң чоң жаныбар?" },
    options: [{ ru: "слон", ky: "пил" }, { ru: "лев", ky: "арстан" }, { ru: "волк", ky: "карышкыр" }], correctIndex: 0,
    explanation: { ru: "Слон — самое большое сухопутное животное.", ky: "Пил — кургактыктагы эң чоң жаныбар." } },
  { id: "g-world3-g", type: "single_choice", subject: "world", topic: "world3", grade: 3, difficulty: 2, free: true,
    prompt: { ru: "Что едят зайцы?", ky: "Коёндор эмне жейт?" },
    options: [{ ru: "морковь", ky: "сабиз" }, { ru: "мясо", ky: "эт" }, { ru: "рыбу", ky: "балык" }], correctIndex: 0,
    explanation: { ru: "Зайцы едят растения, например морковь.", ky: "Коёндор өсүмдүктөрдү, мисалы сабиз жейт." } },
  { id: "g-world3-h", type: "single_choice", subject: "world", topic: "world3", grade: 3, difficulty: 2, free: false,
    prompt: { ru: "Как называется детёныш собаки?", ky: "Иттин баласын кантип аташат?" },
    options: [{ ru: "щенок", ky: "күчүк" }, { ru: "котёнок", ky: "мышыктын баласы" }, { ru: "телёнок", ky: "музоо" }], correctIndex: 0,
    explanation: { ru: "Детёныш собаки — щенок.", ky: "Иттин баласы — күчүк." } },
  { id: "g-world3-i", type: "single_choice", subject: "world", topic: "world3", grade: 3, difficulty: 2, free: false,
    prompt: { ru: "Когда птицы улетают на юг?", ky: "Куштар түштүккө качан учуп кетет?" },
    options: [{ ru: "осенью", ky: "күзүндө" }, { ru: "летом", ky: "жайында" }], correctIndex: 0,
    explanation: { ru: "Птицы улетают на юг осенью.", ky: "Куштар күзүндө түштүккө учуп кетет." } },

  // world4 (4 класс)
  { id: "g-world4-f", type: "number_input", subject: "world", topic: "world4", grade: 4, difficulty: 2, free: true,
    prompt: { ru: "Сколько часов в сутках?", ky: "Бир суткада канча саат бар?" }, answer: 24,
    explanation: { ru: "В сутках 24 часа.", ky: "Бир суткада 24 саат бар." } },
  { id: "g-world4-g", type: "single_choice", subject: "world", topic: "world4", grade: 4, difficulty: 2, free: true,
    prompt: { ru: "Что вращается вокруг Земли?", ky: "Жердин айланасында эмне айланат?" },
    options: [{ ru: "Луна", ky: "Ай" }, { ru: "Солнце", ky: "Күн" }, { ru: "Марс", ky: "Марс" }], correctIndex: 0,
    explanation: { ru: "Вокруг Земли вращается Луна.", ky: "Жердин айланасында Ай айланат." } },
  { id: "g-world4-h", type: "single_choice", subject: "world", topic: "world4", grade: 4, difficulty: 2, free: false,
    prompt: { ru: "Какая на вкус вода в море?", ky: "Деңиздин суусу кандай даамда?" },
    options: [{ ru: "солёная", ky: "туздуу" }, { ru: "сладкая", ky: "таттуу" }], correctIndex: 0,
    explanation: { ru: "Морская вода солёная.", ky: "Деңиз суусу туздуу." } },
  { id: "g-world4-i", type: "single_choice", subject: "world", topic: "world4", grade: 4, difficulty: 2, free: false,
    prompt: { ru: "Какого цвета небо днём в ясную погоду?", ky: "Ачык аба ырайында күндүз асман кандай түстө?" },
    options: [{ ru: "голубое", ky: "көгүлтүр" }, { ru: "зелёное", ky: "жашыл" }, { ru: "красное", ky: "кызыл" }], correctIndex: 0,
    explanation: { ru: "Днём небо голубое.", ky: "Күндүз асман көгүлтүр." } },

  // world5 (5 класс)
  { id: "g-world5-f", type: "number_input", subject: "world", topic: "world5", grade: 5, difficulty: 2, free: true,
    prompt: { ru: "Сколько цветов в радуге?", ky: "Асан-үсөндө канча түс бар?" }, answer: 7,
    explanation: { ru: "В радуге семь цветов.", ky: "Асан-үсөндө жети түс бар." } },
  { id: "g-world5-g", type: "single_choice", subject: "world", topic: "world5", grade: 5, difficulty: 2, free: true,
    prompt: { ru: "Какая звезда согревает Землю?", ky: "Жерди кайсы жылдыз жылытат?" },
    options: [{ ru: "Солнце", ky: "Күн" }, { ru: "Луна", ky: "Ай" }], correctIndex: 0,
    explanation: { ru: "Землю согревает Солнце.", ky: "Жерди Күн жылытат." } },
  { id: "g-world5-h", type: "single_choice", subject: "world", topic: "world5", grade: 5, difficulty: 2, free: false,
    prompt: { ru: "Что замерзает на морозе?", ky: "Аязда эмне катат?" },
    options: [{ ru: "вода", ky: "суу" }, { ru: "камень", ky: "таш" }], correctIndex: 0,
    explanation: { ru: "На морозе замерзает вода.", ky: "Аязда суу катат." } },
  { id: "g-world5-i", type: "single_choice", subject: "world", topic: "world5", grade: 5, difficulty: 2, free: false,
    prompt: { ru: "Где больше всего пресной воды?", ky: "Таза суу эң көп кайда?" },
    options: [{ ru: "в ледниках", ky: "мөңгүлөрдө" }, { ru: "в пустыне", ky: "чөлдө" }], correctIndex: 0,
    explanation: { ru: "Много пресной воды хранится в ледниках.", ky: "Таза суунун көбү мөңгүлөрдө сакталат." } },

  // world6 (6 класс)
  { id: "g-world6-f", type: "single_choice", subject: "world", topic: "world6", grade: 6, difficulty: 2, free: true,
    prompt: { ru: "На каком материке мы живём?", ky: "Биз кайсы материкте жашайбыз?" },
    options: [{ ru: "Евразия", ky: "Евразия" }, { ru: "Африка", ky: "Африка" }, { ru: "Австралия", ky: "Австралия" }], correctIndex: 0,
    explanation: { ru: "Кыргызстан и Россия — в Евразии.", ky: "Кыргызстан менен Россия — Евразияда." } },
  { id: "g-world6-g", type: "single_choice", subject: "world", topic: "world6", grade: 6, difficulty: 2, free: true,
    prompt: { ru: "Самый холодный материк?", ky: "Эң суук материк?" },
    options: [{ ru: "Антарктида", ky: "Антарктида" }, { ru: "Африка", ky: "Африка" }], correctIndex: 0,
    explanation: { ru: "Антарктида — самый холодный материк.", ky: "Антарктида — эң суук материк." } },
  { id: "g-world6-h", type: "single_choice", subject: "world", topic: "world6", grade: 6, difficulty: 2, free: false,
    prompt: { ru: "Что показывает компас?", ky: "Компас эмнени көрсөтөт?" },
    options: [{ ru: "стороны света", ky: "дүйнөнүн тараптарын" }, { ru: "время", ky: "убакытты" }], correctIndex: 0,
    explanation: { ru: "Компас показывает стороны света.", ky: "Компас дүйнөнүн тараптарын көрсөтөт." } },
  { id: "g-world6-i", type: "single_choice", subject: "world", topic: "world6", grade: 6, difficulty: 2, free: false,
    prompt: { ru: "Куда обычно впадают реки?", ky: "Дарыялар адатта кайда куят?" },
    options: [{ ru: "в море", ky: "деңизге" }, { ru: "в гору", ky: "тоого" }], correctIndex: 0,
    explanation: { ru: "Реки впадают в моря и озёра.", ky: "Дарыялар деңиз жана көлдөргө куят." } },

  // world7 (7 класс)
  { id: "g-world7-f", type: "single_choice", subject: "world", topic: "world7", grade: 7, difficulty: 3, free: true,
    prompt: { ru: "Каким органом человек слышит?", ky: "Адам кайсы органы менен угат?" },
    options: [{ ru: "ухо", ky: "кулак" }, { ru: "глаз", ky: "көз" }, { ru: "нос", ky: "мурун" }], correctIndex: 0,
    explanation: { ru: "Мы слышим ушами.", ky: "Биз кулак менен угабыз." } },
  { id: "g-world7-g", type: "number_input", subject: "world", topic: "world7", grade: 7, difficulty: 3, free: true,
    prompt: { ru: "Сколько пальцев на двух руках?", ky: "Эки колдо канча манжа бар?" }, answer: 10,
    explanation: { ru: "На двух руках 10 пальцев.", ky: "Эки колдо 10 манжа бар." } },
  { id: "g-world7-h", type: "single_choice", subject: "world", topic: "world7", grade: 7, difficulty: 3, free: false,
    prompt: { ru: "Что разносит кровь по телу?", ky: "Канды дене боюнча эмне таратат?" },
    options: [{ ru: "сосуды", ky: "кан тамырлар" }, { ru: "кости", ky: "сөөктөр" }], correctIndex: 0,
    explanation: { ru: "Кровь течёт по сосудам.", ky: "Кан тамырлар аркылуу агат." } },
  { id: "g-world7-i", type: "single_choice", subject: "world", topic: "world7", grade: 7, difficulty: 3, free: false,
    prompt: { ru: "Какой орган помогает переваривать пищу?", ky: "Тамакты сиңирүүгө кайсы орган жардам берет?" },
    options: [{ ru: "желудок", ky: "ашказан" }, { ru: "лёгкие", ky: "өпкө" }], correctIndex: 0,
    explanation: { ru: "Пищу переваривает желудок.", ky: "Тамакты ашказан сиңирет." } },

  // world8 (8 класс)
  { id: "g-world8-f", type: "single_choice", subject: "world", topic: "world8", grade: 8, difficulty: 3, free: true,
    prompt: { ru: "Что тяжелее: 1 кг ваты или 1 кг железа?", ky: "Кайсынысы оор: 1 кг макта же 1 кг темир?" },
    options: [{ ru: "одинаково", ky: "бирдей" }, { ru: "железо", ky: "темир" }, { ru: "вата", ky: "макта" }], correctIndex: 0,
    explanation: { ru: "1 кг есть 1 кг — вес одинаковый.", ky: "1 кг — 1 кг, салмагы бирдей." } },
  { id: "g-world8-g", type: "single_choice", subject: "world", topic: "world8", grade: 8, difficulty: 3, free: true,
    prompt: { ru: "В каком состоянии вода при −10 °C?", ky: "−10 °C'та суу кайсы абалда?" },
    options: [{ ru: "лёд", ky: "муз" }, { ru: "пар", ky: "буу" }], correctIndex: 0,
    explanation: { ru: "При −10 °C вода превращается в лёд.", ky: "−10 °C'та суу музга айланат." } },
  { id: "g-world8-h", type: "single_choice", subject: "world", topic: "world8", grade: 8, difficulty: 3, free: false,
    prompt: { ru: "Какой металл притягивает магнит?", ky: "Магнит кайсы металлды тартат?" },
    options: [{ ru: "железо", ky: "темир" }, { ru: "дерево", ky: "жыгач" }, { ru: "стекло", ky: "айнек" }], correctIndex: 0,
    explanation: { ru: "Магнит притягивает железо.", ky: "Магнит темирди тартат." } },
  { id: "g-world8-i", type: "single_choice", subject: "world", topic: "world8", grade: 8, difficulty: 3, free: false,
    prompt: { ru: "Что нужно, чтобы увидеть предметы?", ky: "Буюмдарды көрүү үчүн эмне керек?" },
    options: [{ ru: "свет", ky: "жарык" }, { ru: "звук", ky: "үн" }], correctIndex: 0,
    explanation: { ru: "Чтобы видеть, нужен свет.", ky: "Көрүү үчүн жарык керек." } },

  // world9 (9 класс)
  { id: "g-world9-f", type: "single_choice", subject: "world", topic: "world9", grade: 9, difficulty: 3, free: true,
    prompt: { ru: "Каким символом обозначают углерод?", ky: "Көмүртек кайсы символ менен белгиленет?" },
    options: [{ ru: "C", ky: "C" }, { ru: "O", ky: "O" }, { ru: "H", ky: "H" }], correctIndex: 0,
    explanation: { ru: "Углерод — символ C.", ky: "Көмүртек — C символу." } },
  { id: "g-world9-g", type: "single_choice", subject: "world", topic: "world9", grade: 9, difficulty: 3, free: true,
    prompt: { ru: "В каких единицах измеряют мощность?", ky: "Кубаттуулук кайсы бирдикте өлчөнөт?" },
    options: [{ ru: "Ватт", ky: "Ватт" }, { ru: "Ньютон", ky: "Ньютон" }, { ru: "Метр", ky: "Метр" }], correctIndex: 0,
    explanation: { ru: "Мощность измеряют в ваттах.", ky: "Кубаттуулук ватт менен өлчөнөт." } },
  { id: "g-world9-h", type: "single_choice", subject: "world", topic: "world9", grade: 9, difficulty: 3, free: false,
    prompt: { ru: "Что хорошо проводит электрический ток?", ky: "Электр тогун эмне жакшы өткөрөт?" },
    options: [{ ru: "металл", ky: "металл" }, { ru: "дерево", ky: "жыгач" }, { ru: "резина", ky: "резина" }], correctIndex: 0,
    explanation: { ru: "Металлы хорошо проводят ток.", ky: "Металлдар токту жакшы өткөрөт." } },
  { id: "g-world9-i", type: "single_choice", subject: "world", topic: "world9", grade: 9, difficulty: 3, free: false,
    prompt: { ru: "Как называется положительно заряженная частица атома?", ky: "Атомдун оң зарядуу бөлүкчөсү кантип аталат?" },
    options: [{ ru: "протон", ky: "протон" }, { ru: "электрон", ky: "электрон" }], correctIndex: 0,
    explanation: { ru: "Положительный заряд у протона.", ky: "Оң заряд протондо." } },

  // world10 (10 класс)
  { id: "g-world10-g", type: "single_choice", subject: "world", topic: "world10", grade: 10, difficulty: 3, free: true,
    prompt: { ru: "Как называется наша галактика?", ky: "Биздин галактика кантип аталат?" },
    options: [{ ru: "Млечный Путь", ky: "Саманчынын жолу" }, { ru: "Андромеда", ky: "Андромеда" }], correctIndex: 0,
    explanation: { ru: "Наша галактика — Млечный Путь.", ky: "Биздин галактика — Саманчынын жолу." } },
  { id: "g-world10-h", type: "single_choice", subject: "world", topic: "world10", grade: 10, difficulty: 3, free: true,
    prompt: { ru: "Что излучает Солнце?", ky: "Күн эмне чыгарат?" },
    options: [{ ru: "свет и тепло", ky: "жарык жана жылуулук" }, { ru: "только холод", ky: "суук гана" }], correctIndex: 0,
    explanation: { ru: "Солнце излучает свет и тепло.", ky: "Күн жарык жана жылуулук чыгарат." } },
  { id: "g-world10-i", type: "single_choice", subject: "world", topic: "world10", grade: 10, difficulty: 3, free: false,
    prompt: { ru: "Твёрдое тело сохраняет что?", ky: "Катуу дене эмнесин сактайт?" },
    options: [{ ru: "форму", ky: "формасын" }, { ru: "запах", ky: "жытын" }], correctIndex: 0,
    explanation: { ru: "Твёрдое тело сохраняет форму.", ky: "Катуу дене формасын сактайт." } },
  { id: "g-world10-j", type: "single_choice", subject: "world", topic: "world10", grade: 10, difficulty: 3, free: false,
    prompt: { ru: "Что происходит с водой при нагревании до 100 °C?", ky: "100 °C'ка чейин ысыганда суу менен эмне болот?" },
    options: [{ ru: "кипит", ky: "кайнайт" }, { ru: "замерзает", ky: "катат" }], correctIndex: 0,
    explanation: { ru: "При 100 °C вода кипит.", ky: "100 °C'та суу кайнайт." } },

  // world11 (11 класс)
  { id: "g-world11-f", type: "single_choice", subject: "world", topic: "world11", grade: 11, difficulty: 3, free: true,
    prompt: { ru: "Из чего в основном состоит Солнце?", ky: "Күн негизинен эмнеден турат?" },
    options: [{ ru: "из газа", ky: "газдан" }, { ru: "из камня", ky: "таштан" }], correctIndex: 0,
    explanation: { ru: "Солнце состоит в основном из раскалённого газа.", ky: "Күн негизинен ысык газдан турат." } },
  { id: "g-world11-g", type: "single_choice", subject: "world", topic: "world11", grade: 11, difficulty: 3, free: true,
    prompt: { ru: "Кто первым полетел в космос?", ky: "Космоско биринчи ким учкан?" },
    options: [{ ru: "Юрий Гагарин", ky: "Юрий Гагарин" }, { ru: "Нил Армстронг", ky: "Нил Армстронг" }], correctIndex: 0,
    explanation: { ru: "Первым в космос полетел Юрий Гагарин.", ky: "Космоско биринчи Юрий Гагарин учкан." } },
  { id: "g-world11-h", type: "number_input", subject: "world", topic: "world11", grade: 11, difficulty: 3, free: false,
    prompt: { ru: "Сколько секунд в одной минуте?", ky: "Бир мүнөттө канча секунд бар?" }, answer: 60,
    explanation: { ru: "В минуте 60 секунд.", ky: "Бир мүнөттө 60 секунд бар." } },
  { id: "g-world11-i", type: "single_choice", subject: "world", topic: "world11", grade: 11, difficulty: 3, free: false,
    prompt: { ru: "Какое небесное тело вызывает приливы на Земле?", ky: "Жерде толкундарды кайсы асман нерсеси пайда кылат?" },
    options: [{ ru: "Луна", ky: "Ай" }, { ru: "Марс", ky: "Марс" }], correctIndex: 0,
    explanation: { ru: "Приливы вызывает притяжение Луны.", ky: "Толкундарды Айдын тартылуусу пайда кылат." } },
];

export const higherTasks: Task[] = [
  ...LOGIC,
  ...READING,
  ...WORLD,
  ...WORLD_LOWER,
  ...WORLD_TOPUP,
  ...MATH,
];
