import type { Task } from "./types";

// «Задания со звёздочкой» — по одному челленджу в каждую тему (0–11).
// Чуть сложнее остальных заданий рубрики; помечаются star: true и идут
// последними в теме. Все — бесплатные и видны всем.

export const starTasks: Task[] = [
  // ── Подготовка к школе (0) ──
  {
    id: "star-pre-count", type: "number_input", subject: "math", topic: "pre-count", grade: 0,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "Сколько будет, если к 3 добавить 2?", ky: "3кө 2 кошсок канча болот?" },
    answer: 5,
    explanation: { ru: "3 + 2 = 5.", ky: "3 + 2 = 5." },
  },
  {
    id: "star-pre-more", type: "number_input", subject: "math", topic: "pre-more", grade: 0,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "На сколько 5 больше, чем 3?", ky: "5 3төн канчага көп?" },
    answer: 2,
    explanation: { ru: "5 − 3 = 2.", ky: "5 − 3 = 2." },
  },
  {
    id: "star-pre-odd", type: "single_choice", subject: "logic", topic: "pre-odd", grade: 0,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "Что здесь лишнее?", ky: "Бул жерде эмне ашык?" },
    options: [{ ru: "яблоко", ky: "алма" }, { ru: "груша", ky: "алмурут" }, { ru: "банан", ky: "банан" }, { ru: "машина", ky: "машине" }],
    correctIndex: 3,
    explanation: { ru: "Машина — не фрукт.", ky: "Машине — мөмө эмес." },
  },
  {
    id: "star-pre-shapes", type: "number_input", subject: "logic", topic: "pre-shapes", grade: 0,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "Сколько углов у треугольника?", ky: "Үч бурчтуктун канча бурчу бар?" },
    answer: 3,
    explanation: { ru: "У треугольника три угла.", ky: "Үч бурчтуктун үч бурчу бар." },
  },
  {
    id: "star-pre-letters", type: "single_choice", subject: "reading", topic: "pre-letters", grade: 0,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "Какая из букв гласная?", ky: "Кайсы тамга үндүү?" },
    options: [{ ru: "М", ky: "М" }, { ru: "О", ky: "О" }, { ru: "Т", ky: "Т" }],
    correctIndex: 1,
    explanation: { ru: "О — гласная буква.", ky: "О — үндүү тамга." },
  },
  {
    id: "star-pre-seq", type: "number_input", subject: "logic", topic: "pre-seq", grade: 0,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "Что дальше: 2, 4, 6, 8, ?", ky: "Андан ары эмне: 2, 4, 6, 8, ?" },
    answer: 10,
    explanation: { ru: "Прибавляем по 2: 10.", ky: "2ден кошобуз: 10." },
  },
  {
    id: "star-pre-big", type: "single_choice", subject: "logic", topic: "pre-big", grade: 0,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "Кто самый большой?", ky: "Кимиси эң чоң?" },
    options: [{ ru: "муравей", ky: "кумурска" }, { ru: "кошка", ky: "мышык" }, { ru: "слон", ky: "пил" }],
    correctIndex: 2,
    explanation: { ru: "Слон самый большой.", ky: "Пил эң чоң." },
  },

  // ── 1 класс ──
  {
    id: "star-log-odd", type: "single_choice", subject: "logic", topic: "log-odd", grade: 1,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "Какое число лишнее: 2, 4, 7, 8?", ky: "Кайсы сан ашык: 2, 4, 7, 8?" },
    options: [{ ru: "2", ky: "2" }, { ru: "4", ky: "4" }, { ru: "7", ky: "7" }, { ru: "8", ky: "8" }],
    correctIndex: 2,
    explanation: { ru: "7 — нечётное, остальные чётные.", ky: "7 — так, калгандары жуп." },
  },
  {
    id: "star-log-seq", type: "number_input", subject: "logic", topic: "log-seq", grade: 1,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "Продолжи ряд: 1, 3, 5, 7, ?", ky: "Катарды улант: 1, 3, 5, 7, ?" },
    answer: 9,
    explanation: { ru: "Нечётные числа: 9.", ky: "Так сандар: 9." },
  },
  {
    id: "star-math-count", type: "number_input", subject: "math", topic: "math-count", grade: 1,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "7 + 5 = ?", ky: "7 + 5 = ?" },
    answer: 12,
    explanation: { ru: "7 + 5 = 12.", ky: "7 + 5 = 12." },
  },
  {
    id: "star-math-add", type: "number_input", subject: "math", topic: "math-add", grade: 1,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "12 − 5 + 3 = ?", ky: "12 − 5 + 3 = ?" },
    answer: 10,
    explanation: { ru: "12 − 5 = 7, 7 + 3 = 10.", ky: "12 − 5 = 7, 7 + 3 = 10." },
  },
  {
    id: "star-read-letters", type: "single_choice", subject: "reading", topic: "read-letters", grade: 1,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "Какая буква идёт перед «Д»?", ky: "«Д» тамгасынан мурун кайсы тамга турат?" },
    options: [{ ru: "Г", ky: "Г" }, { ru: "В", ky: "В" }, { ru: "Е", ky: "Е" }],
    correctIndex: 0,
    explanation: { ru: "Перед «Д» идёт «Г».", ky: "«Д»дан мурун «Г» турат." },
  },
  {
    id: "star-math-ten", type: "number_input", subject: "math", topic: "math-ten", grade: 1,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "8 + 7 = ?", ky: "8 + 7 = ?" },
    answer: 15,
    explanation: { ru: "8 + 7 = 15.", ky: "8 + 7 = 15." },
  },
  {
    id: "star-math-compare", type: "number_input", subject: "math", topic: "math-compare", grade: 1,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "На сколько 9 больше 4?", ky: "9 4төн канчага көп?" },
    answer: 5,
    explanation: { ru: "9 − 4 = 5.", ky: "9 − 4 = 5." },
  },
  {
    id: "star-read-vowels", type: "number_input", subject: "reading", topic: "read-vowels", grade: 1,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "Сколько гласных среди букв: А, М, О, П, У?", ky: "Тамгалардын арасында канча үндүү: А, М, О, П, У?" },
    answer: 3,
    explanation: { ru: "Гласные А, О, У — их три.", ky: "Үндүүлөр А, О, У — үчөө." },
  },
  {
    id: "star-world1", type: "number_input", subject: "world", topic: "world1", grade: 1,
    difficulty: 2, free: true, star: true,
    prompt: { ru: "Сколько лап у кошки и собаки вместе?", ky: "Мышык менен иттин бардык буттарынын саны?" },
    answer: 8,
    explanation: { ru: "4 + 4 = 8.", ky: "4 + 4 = 8." },
  },

  // ── 2 класс ──
  {
    id: "star-log-think", type: "number_input", subject: "logic", topic: "log-think", grade: 2,
    difficulty: 3, free: true, star: true,
    prompt: {
      ru: "У Ани 3 яблока, у Бори на 2 больше. Сколько всего яблок у них?",
      ky: "Анада 3 алма, Борада 2 көп. Экөөндө бардыгы канча алма?",
    },
    answer: 8,
    explanation: { ru: "У Бори 5, всего 3 + 5 = 8.", ky: "Борада 5, бардыгы 3 + 5 = 8." },
  },
  {
    id: "star-math-seq", type: "number_input", subject: "math", topic: "math-seq", grade: 2,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Продолжи ряд: 5, 10, 15, 20, ?", ky: "Катарды улант: 5, 10, 15, 20, ?" },
    answer: 25,
    explanation: { ru: "Прибавляем по 5: 25.", ky: "5тен кошобуз: 25." },
  },
  {
    id: "star-math-tens", type: "number_input", subject: "math", topic: "math-tens", grade: 2,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "45 + 27 = ?", ky: "45 + 27 = ?" },
    answer: 72,
    explanation: { ru: "45 + 27 = 72.", ky: "45 + 27 = 72." },
  },
  {
    id: "star-math-mult", type: "number_input", subject: "math", topic: "math-mult", grade: 2,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "6 × 7 = ?", ky: "6 × 7 = ?" },
    answer: 42,
    explanation: { ru: "6 × 7 = 42.", ky: "6 × 7 = 42." },
  },
  {
    id: "star-math-word", type: "number_input", subject: "math", topic: "math-word", grade: 2,
    difficulty: 3, free: true, star: true,
    prompt: {
      ru: "В корзине было 20 яблок. Съели 8, потом добавили 5. Сколько стало?",
      ky: "Себетте 20 алма бар эле. 8ин жеди, анан 5 кошту. Канча болду?",
    },
    answer: 17,
    explanation: { ru: "20 − 8 = 12, 12 + 5 = 17.", ky: "20 − 8 = 12, 12 + 5 = 17." },
  },
  {
    id: "star-read-words", type: "number_input", subject: "reading", topic: "read-words", grade: 2,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько слов в предложении: «Птицы поют весело»?", ky: "«Куштар шаттуу сайрайт» сүйлөмүндө канча сөз?" },
    answer: 3,
    explanation: { ru: "Слова: три.", ky: "Сөздөр: үчөө." },
  },
  {
    id: "star-world2", type: "number_input", subject: "world", topic: "world2", grade: 2,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько месяцев длится каждое время года?", ky: "Ар бир жыл мезгили канча айга созулат?" },
    answer: 3,
    explanation: { ru: "12 месяцев ÷ 4 сезона = 3.", ky: "12 ай ÷ 4 мезгил = 3." },
  },

  // ── 3 класс ──
  {
    id: "star-m3-mult", type: "number_input", subject: "math", topic: "m3-mult", grade: 3,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "12 × 8 = ?", ky: "12 × 8 = ?" },
    answer: 96,
    explanation: { ru: "12 × 8 = 96.", ky: "12 × 8 = 96." },
  },
  {
    id: "star-m3-div", type: "number_input", subject: "math", topic: "m3-div", grade: 3,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "96 ÷ 8 = ?", ky: "96 ÷ 8 = ?" },
    answer: 12,
    explanation: { ru: "96 ÷ 8 = 12.", ky: "96 ÷ 8 = 12." },
  },
  {
    id: "star-m3-big", type: "number_input", subject: "math", topic: "m3-big", grade: 3,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "347 + 256 = ?", ky: "347 + 256 = ?" },
    answer: 603,
    explanation: { ru: "347 + 256 = 603.", ky: "347 + 256 = 603." },
  },
  {
    id: "star-log3", type: "number_input", subject: "logic", topic: "log3", grade: 3,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Продолжи ряд: 2, 3, 5, 8, 12, ?", ky: "Катарды улант: 2, 3, 5, 8, 12, ?" },
    answer: 17,
    explanation: { ru: "Разности 1, 2, 3, 4, 5: 12 + 5 = 17.", ky: "Айырмалар 1, 2, 3, 4, 5: 12 + 5 = 17." },
  },
  {
    id: "star-read3", type: "number_input", subject: "reading", topic: "read3", grade: 3,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько предложений: «Утро. Солнце встало. Птицы поют.»?", ky: "Канча сүйлөм: «Эртең менен. Күн чыкты. Куштар сайрайт.»?" },
    answer: 3,
    explanation: { ru: "Три предложения.", ky: "Үч сүйлөм." },
  },
  {
    id: "star-world3", type: "single_choice", subject: "world", topic: "world3", grade: 3,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Кто из них НЕ насекомое?", ky: "Булардын кайсынысы курт-кумурска ЭМЕС?" },
    options: [{ ru: "муравей", ky: "кумурска" }, { ru: "паук", ky: "жөргөмүш" }, { ru: "пчела", ky: "аары" }],
    correctIndex: 1,
    explanation: { ru: "У паука 8 ног — он не насекомое.", ky: "Жөргөмүштүн 8 буту бар — ал курт-кумурска эмес." },
  },

  // ── 4 класс ──
  {
    id: "star-m4-mult", type: "number_input", subject: "math", topic: "m4-mult", grade: 4,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "144 ÷ 12 = ?", ky: "144 ÷ 12 = ?" },
    answer: 12,
    explanation: { ru: "144 ÷ 12 = 12.", ky: "144 ÷ 12 = 12." },
  },
  {
    id: "star-m4-order", type: "number_input", subject: "math", topic: "m4-order", grade: 4,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "20 − 2 × 5 = ?", ky: "20 − 2 × 5 = ?" },
    answer: 10,
    explanation: { ru: "Сначала умножение: 2 × 5 = 10, потом 20 − 10 = 10.", ky: "Адегенде көбөйтүү: 2 × 5 = 10, анан 20 − 10 = 10." },
  },
  {
    id: "star-m4-frac", type: "number_input", subject: "math", topic: "m4-frac", grade: 4,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько будет ¾ от 20?", ky: "20дун ¾ канча болот?" },
    answer: 15,
    explanation: { ru: "20 ÷ 4 = 5, 5 × 3 = 15.", ky: "20 ÷ 4 = 5, 5 × 3 = 15." },
  },
  {
    id: "star-log4", type: "number_input", subject: "logic", topic: "log4", grade: 4,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Продолжи ряд: 1, 4, 9, 16, 25, ?", ky: "Катарды улант: 1, 4, 9, 16, 25, ?" },
    answer: 36,
    explanation: { ru: "Квадраты: 6 × 6 = 36.", ky: "Квадраттар: 6 × 6 = 36." },
  },
  {
    id: "star-read4", type: "number_input", subject: "reading", topic: "read4", grade: 4,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько гласных среди букв: А, О, Е, Б, К?", ky: "Тамгалардын арасында канча үндүү: А, О, Е, Б, К?" },
    answer: 3,
    explanation: { ru: "Гласные А, О, Е — их три.", ky: "Үндүүлөр А, О, Е — үчөө." },
  },
  {
    id: "star-world4", type: "number_input", subject: "world", topic: "world4", grade: 4,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько часов в двух сутках?", ky: "Эки суткада канча саат бар?" },
    answer: 48,
    explanation: { ru: "24 × 2 = 48.", ky: "24 × 2 = 48." },
  },

  // ── 5 класс ──
  {
    id: "star-m5-percent", type: "number_input", subject: "math", topic: "m5-percent", grade: 5,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько будет 20% от 350?", ky: "350дүн 20% канча болот?" },
    answer: 70,
    explanation: { ru: "350 ÷ 100 × 20 = 70.", ky: "350 ÷ 100 × 20 = 70." },
  },
  {
    id: "star-m5-frac", type: "number_input", subject: "math", topic: "m5-frac", grade: 5,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько будет ⅗ от 25?", ky: "25тин ⅗ канча болот?" },
    answer: 15,
    explanation: { ru: "25 ÷ 5 = 5, 5 × 3 = 15.", ky: "25 ÷ 5 = 5, 5 × 3 = 15." },
  },
  {
    id: "star-m5-big", type: "number_input", subject: "math", topic: "m5-big", grade: 5,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "1250 + 3750 = ?", ky: "1250 + 3750 = ?" },
    answer: 5000,
    explanation: { ru: "1250 + 3750 = 5000.", ky: "1250 + 3750 = 5000." },
  },
  {
    id: "star-log5", type: "number_input", subject: "logic", topic: "log5", grade: 5,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Продолжи ряд: 2, 6, 12, 20, 30, ?", ky: "Катарды улант: 2, 6, 12, 20, 30, ?" },
    answer: 42,
    explanation: { ru: "Разности 4, 6, 8, 10, 12: 30 + 12 = 42.", ky: "Айырмалар 4, 6, 8, 10, 12: 30 + 12 = 42." },
  },
  {
    id: "star-read5", type: "single_choice", subject: "reading", topic: "read5", grade: 5,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Найди слово, которое НЕ существительное", ky: "Зат атооч ЭМЕС сөздү тап" },
    options: [{ ru: "стол", ky: "үстөл" }, { ru: "окно", ky: "терезе" }, { ru: "бежать", ky: "чуркоо" }],
    correctIndex: 2,
    explanation: { ru: "«Бежать» — глагол, а не существительное.", ky: "«Чуркоо» — этиш, зат атооч эмес." },
  },
  {
    id: "star-world5", type: "single_choice", subject: "world", topic: "world5", grade: 5,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Какая планета третья от Солнца?", ky: "Күндөн үчүнчү планета кайсы?" },
    options: [{ ru: "Земля", ky: "Жер" }, { ru: "Марс", ky: "Марс" }, { ru: "Венера", ky: "Венера" }],
    correctIndex: 0,
    explanation: { ru: "Порядок: Меркурий, Венера, Земля.", ky: "Ирети: Меркурий, Венера, Жер." },
  },

  // ── 6 класс ──
  {
    id: "star-m6-neg", type: "number_input", subject: "math", topic: "m6-neg", grade: 6,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "−5 + 8 − 3 = ?", ky: "−5 + 8 − 3 = ?" },
    answer: 0,
    explanation: { ru: "−5 + 8 = 3, 3 − 3 = 0.", ky: "−5 + 8 = 3, 3 − 3 = 0." },
  },
  {
    id: "star-m6-eq", type: "number_input", subject: "math", topic: "m6-eq", grade: 6,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Реши: 3x + 5 = 20. Чему равен x?", ky: "Чеч: 3x + 5 = 20. x канчага барабар?" },
    answer: 5,
    explanation: { ru: "3x = 15, x = 5.", ky: "3x = 15, x = 5." },
  },
  {
    id: "star-m6-percent", type: "number_input", subject: "math", topic: "m6-percent", grade: 6,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Товар стоит 500. Скидка 20%. Новая цена?", ky: "Товар 500 турат. Арзандатуу 20%. Жаңы баасы?" },
    answer: 400,
    explanation: { ru: "20% от 500 = 100, 500 − 100 = 400.", ky: "500дүн 20% = 100, 500 − 100 = 400." },
  },
  {
    id: "star-log6", type: "number_input", subject: "logic", topic: "log6", grade: 6,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Продолжи ряд: 1, 2, 4, 7, 11, 16, ?", ky: "Катарды улант: 1, 2, 4, 7, 11, 16, ?" },
    answer: 22,
    explanation: { ru: "Разности 1, 2, 3, 4, 5, 6: 16 + 6 = 22.", ky: "Айырмалар 1, 2, 3, 4, 5, 6: 16 + 6 = 22." },
  },
  {
    id: "star-read6", type: "single_choice", subject: "reading", topic: "read6", grade: 6,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Найди антоним к слову «начало»", ky: "«Башталышы» сөзүнө антонимди тап" },
    options: [{ ru: "конец", ky: "аягы" }, { ru: "середина", ky: "ортосу" }, { ru: "край", ky: "чети" }],
    correctIndex: 0,
    explanation: { ru: "«Конец» — противоположность «начала».", ky: "«Аягы» — «башталышы» дегендин карама-каршысы." },
  },
  {
    id: "star-world6", type: "single_choice", subject: "world", topic: "world6", grade: 6,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "На каком материке находится пустыня Сахара?", ky: "Сахара чөлү кайсы материкте жайгашкан?" },
    options: [{ ru: "Африка", ky: "Африка" }, { ru: "Азия", ky: "Азия" }, { ru: "Европа", ky: "Европа" }],
    correctIndex: 0,
    explanation: { ru: "Сахара находится в Африке.", ky: "Сахара Африкада жайгашкан." },
  },

  // ── 7 класс ──
  {
    id: "star-m7-pow", type: "number_input", subject: "math", topic: "m7-pow", grade: 7,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "2⁵ = ?", ky: "2⁵ = ?" },
    answer: 32,
    explanation: { ru: "2 × 2 × 2 × 2 × 2 = 32.", ky: "2 × 2 × 2 × 2 × 2 = 32." },
  },
  {
    id: "star-m7-eq", type: "number_input", subject: "math", topic: "m7-eq", grade: 7,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Реши: 5x − 7 = 18. Чему равен x?", ky: "Чеч: 5x − 7 = 18. x канчага барабар?" },
    answer: 5,
    explanation: { ru: "5x = 25, x = 5.", ky: "5x = 25, x = 5." },
  },
  {
    id: "star-log7", type: "number_input", subject: "logic", topic: "log7", grade: 7,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Продолжи ряд: 3, 6, 12, 24, 48, ?", ky: "Катарды улант: 3, 6, 12, 24, 48, ?" },
    answer: 96,
    explanation: { ru: "Каждое число в 2 раза больше: 48 × 2 = 96.", ky: "Ар бир сан 2 эсе чоң: 48 × 2 = 96." },
  },
  {
    id: "star-read7", type: "single_choice", subject: "reading", topic: "read7", grade: 7,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Найди лишнее (не родственное) слово", ky: "Ашык (тектеш эмес) сөздү тап" },
    options: [{ ru: "гора", ky: "тоо" }, { ru: "горный", ky: "тоолуу" }, { ru: "город", ky: "шаар" }, { ru: "горка", ky: "дөбө" }],
    correctIndex: 2,
    explanation: { ru: "«Город» не связан с «горой» по смыслу.", ky: "«Шаар» «тоо» менен маанилеш эмес." },
  },
  {
    id: "star-world7", type: "number_input", subject: "world", topic: "world7", grade: 7,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько пар рёбер у человека?", ky: "Адамда канча жуп кабырга бар?" },
    answer: 12,
    explanation: { ru: "У человека 12 пар рёбер.", ky: "Адамда 12 жуп кабырга бар." },
  },
  {
    id: "star-m7-geo", type: "number_input", subject: "math", topic: "m7-geo", grade: 7,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Площадь квадрата со стороной 12?", ky: "Тарабы 12 болгон чарчынын аянты?" },
    answer: 144,
    explanation: { ru: "12 × 12 = 144.", ky: "12 × 12 = 144." },
  },

  // ── 8 класс ──
  {
    id: "star-m8-sqrt", type: "number_input", subject: "math", topic: "m8-sqrt", grade: 8,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "√196 = ?", ky: "√196 = ?" },
    answer: 14,
    explanation: { ru: "14 × 14 = 196.", ky: "14 × 14 = 196." },
  },
  {
    id: "star-m8-pow", type: "number_input", subject: "math", topic: "m8-pow", grade: 8,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "3⁴ = ?", ky: "3⁴ = ?" },
    answer: 81,
    explanation: { ru: "3 × 3 × 3 × 3 = 81.", ky: "3 × 3 × 3 × 3 = 81." },
  },
  {
    id: "star-m8-eq", type: "number_input", subject: "math", topic: "m8-eq", grade: 8,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Реши: 2x + 3 = x + 10. Чему равен x?", ky: "Чеч: 2x + 3 = x + 10. x канчага барабар?" },
    answer: 7,
    explanation: { ru: "2x − x = 10 − 3, x = 7.", ky: "2x − x = 10 − 3, x = 7." },
  },
  {
    id: "star-log8", type: "number_input", subject: "logic", topic: "log8", grade: 8,
    difficulty: 3, free: true, star: true,
    prompt: {
      ru: "В классе 30 учеников. 20 учат английский, 15 немецкий, 8 — оба. Сколько не учат ни один?",
      ky: "Класста 30 окуучу. 20 англис, 15 немис тилин үйрөнөт, 8 — экөөнү тең. Канчасы бирин да үйрөнбөйт?",
    },
    answer: 3,
    explanation: { ru: "Хотя бы один язык: 20 + 15 − 8 = 27. Ни одного: 30 − 27 = 3.", ky: "Жок дегенде бир тил: 20 + 15 − 8 = 27. Бирин да: 30 − 27 = 3." },
  },
  {
    id: "star-read8", type: "number_input", subject: "reading", topic: "read8", grade: 8,
    difficulty: 3, free: true, star: true,
    prompt: {
      ru: "Сколько грамматических основ: «Солнце село, стало темно, зажглись звёзды»?",
      ky: "Канча грамматикалык негиз: «Күн батты, караңгы болду, жылдыздар жанды»?",
    },
    answer: 3,
    explanation: { ru: "Три основы — три части сложного предложения.", ky: "Үч негиз — татаал сүйлөмдүн үч бөлүгү." },
  },
  {
    id: "star-world8", type: "number_input", subject: "world", topic: "world8", grade: 8,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько всего атомов в молекуле CO₂?", ky: "CO₂ молекуласында бардыгы канча атом бар?" },
    answer: 3,
    explanation: { ru: "1 углерод + 2 кислорода = 3 атома.", ky: "1 көмүртек + 2 кычкылтек = 3 атом." },
  },
  {
    id: "star-m8-geo", type: "number_input", subject: "math", topic: "m8-geo", grade: 8,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Гипотенуза при катетах 9 и 12?", ky: "Катеттери 9 жана 12 болгондо гипотенуза?" },
    answer: 15,
    explanation: { ru: "√(9² + 12²) = √225 = 15.", ky: "√(9² + 12²) = √225 = 15." },
  },

  // ── 9 класс ──
  {
    id: "star-m9-prog", type: "number_input", subject: "math", topic: "m9-prog", grade: 9,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Арифметическая прогрессия 3, 7, 11, … Найди 5-й член.", ky: "Арифметикалык прогрессия 3, 7, 11, … 5-мүчөсүн тап." },
    answer: 19,
    explanation: { ru: "Разность 4: 3 + 4 × 4 = 19.", ky: "Айырма 4: 3 + 4 × 4 = 19." },
  },
  {
    id: "star-m9-pow", type: "number_input", subject: "math", topic: "m9-pow", grade: 9,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "2⁷ = ?", ky: "2⁷ = ?" },
    answer: 128,
    explanation: { ru: "2 в 7-й степени = 128.", ky: "2нин 7-даражасы = 128." },
  },
  {
    id: "star-m9-root", type: "number_input", subject: "math", topic: "m9-root", grade: 9,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "√225 = ?", ky: "√225 = ?" },
    answer: 15,
    explanation: { ru: "15 × 15 = 225.", ky: "15 × 15 = 225." },
  },
  {
    id: "star-m9-eq", type: "number_input", subject: "math", topic: "m9-eq", grade: 9,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "x² − 9 = 0. Положительный корень?", ky: "x² − 9 = 0. Оң тамыры?" },
    answer: 3,
    explanation: { ru: "x² = 9, x = 3.", ky: "x² = 9, x = 3." },
  },
  {
    id: "star-log9", type: "number_input", subject: "logic", topic: "log9", grade: 9,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколькими способами выбрать 2 предмета из 4?", ky: "4 буюмдан 2ни канча жол менен тандаса болот?" },
    answer: 6,
    explanation: { ru: "C(4,2) = 6.", ky: "C(4,2) = 6." },
  },
  {
    id: "star-world9", type: "number_input", subject: "world", topic: "world9", grade: 9,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько протонов в атоме кислорода (номер 8)?", ky: "Кычкылтек атомунда канча протон бар (номери 8)?" },
    answer: 8,
    explanation: { ru: "Номер элемента равен числу протонов: 8.", ky: "Элементтин номери протондордун санына барабар: 8." },
  },
  {
    id: "star-m9-geo", type: "number_input", subject: "math", topic: "m9-geo", grade: 9,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Площадь круга радиуса 10 (принять π ≈ 3)?", ky: "Радиусу 10 болгон тегеректин аянты (π ≈ 3)?" },
    answer: 300,
    explanation: { ru: "π × r² ≈ 3 × 100 = 300.", ky: "π × r² ≈ 3 × 100 = 300." },
  },
  {
    id: "star-read9", type: "single_choice", subject: "reading", topic: "read9", grade: 9,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "В каком значении слово «горит» в «горит на работе»?", ky: "«Иште күйүп жанат» дегенде «күйүп жанат» кайсы мааниде?" },
    options: [{ ru: "переносном", ky: "өтмө" }, { ru: "прямом", ky: "түз" }],
    correctIndex: 0,
    explanation: { ru: "Здесь «горит» — увлечён, значение переносное.", ky: "Бул жерде «күйүп жанат» — берилген, мааниси өтмө." },
  },

  // ── 10 класс ──
  {
    id: "star-m10-calc", type: "number_input", subject: "math", topic: "m10-calc", grade: 10,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "√400 + 10% от 50 = ?", ky: "√400 + 50дүн 10% = ?" },
    answer: 25,
    explanation: { ru: "20 + 5 = 25.", ky: "20 + 5 = 25." },
  },
  {
    id: "star-m10-pow", type: "number_input", subject: "math", topic: "m10-pow", grade: 10,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "5⁴ = ?", ky: "5⁴ = ?" },
    answer: 625,
    explanation: { ru: "5 × 5 × 5 × 5 = 625.", ky: "5 × 5 × 5 × 5 = 625." },
  },
  {
    id: "star-log10", type: "single_choice", subject: "logic", topic: "log10", grade: 10,
    difficulty: 3, free: true, star: true,
    prompt: {
      ru: "«Если A, то B» истинно, но B ложно. Что можно сказать об A?",
      ky: "«Эгер A болсо, B» чын, бирок B жалган. A жөнүндө эмне айтууга болот?",
    },
    options: [{ ru: "A ложно", ky: "A жалган" }, { ru: "A истинно", ky: "A чын" }, { ru: "неизвестно", ky: "белгисиз" }],
    correctIndex: 0,
    explanation: { ru: "Если бы A было истинно, B тоже было бы истинно. Значит A ложно.", ky: "A чын болсо, B да чын болмок. Демек A жалган." },
  },
  {
    id: "star-world10", type: "number_input", subject: "world", topic: "world10", grade: 10,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько планет-гигантов в Солнечной системе?", ky: "Күн системасында канча алп планета бар?" },
    answer: 4,
    explanation: { ru: "Юпитер, Сатурн, Уран, Нептун — четыре.", ky: "Юпитер, Сатурн, Уран, Нептун — төртөө." },
  },
  {
    id: "star-m10-eq", type: "number_input", subject: "math", topic: "m10-eq", grade: 10,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "x² − 10x + 21 = 0. Больший корень?", ky: "x² − 10x + 21 = 0. Чоң тамыры?" },
    answer: 7,
    explanation: { ru: "Корни 3 и 7 (3 × 7 = 21, 3 + 7 = 10). Больший — 7.", ky: "Тамырлар 3 жана 7 (3 × 7 = 21, 3 + 7 = 10). Чоңу — 7." },
  },
  {
    id: "star-read10", type: "number_input", subject: "reading", topic: "read10", grade: 10,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько грамматических основ: «Я знаю, что ты придёшь»?", ky: "Канча грамматикалык негиз: «Мен билем, сен келесиң»?" },
    answer: 2,
    explanation: { ru: "«Я знаю» и «ты придёшь» — две основы.", ky: "«Мен билем» жана «сен келесиң» — эки негиз." },
  },

  // ── 11 класс ──
  {
    id: "star-m11-calc", type: "number_input", subject: "math", topic: "m11-calc", grade: 11,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "2⁶ + √49 = ?", ky: "2⁶ + √49 = ?" },
    answer: 71,
    explanation: { ru: "64 + 7 = 71.", ky: "64 + 7 = 71." },
  },
  {
    id: "star-log11", type: "number_input", subject: "logic", topic: "log11", grade: 11,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько диагоналей у восьмиугольника?", ky: "Сегиз бурчтуктун канча диагоналы бар?" },
    answer: 20,
    explanation: { ru: "n(n−3)/2 = 8 × 5 / 2 = 20.", ky: "n(n−3)/2 = 8 × 5 / 2 = 20." },
  },
  {
    id: "star-world11", type: "number_input", subject: "world", topic: "world11", grade: 11,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Сколько примерно минут свет идёт от Солнца до Земли?", ky: "Күндөн Жерге жарык болжол менен канча мүнөттө жетет?" },
    answer: 8,
    explanation: { ru: "Свет идёт около 8 минут.", ky: "Жарык болжол менен 8 мүнөттө жетет." },
  },
  {
    id: "star-m11-geo", type: "number_input", subject: "math", topic: "m11-geo", grade: 11,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Объём куба с ребром 6?", ky: "Кыры 6 болгон кубдун көлөмү?" },
    answer: 216,
    explanation: { ru: "6³ = 216.", ky: "6³ = 216." },
  },
  {
    id: "star-read11", type: "single_choice", subject: "reading", topic: "read11", grade: 11,
    difficulty: 3, free: true, star: true,
    prompt: { ru: "Найди лишнее слово по части речи", ky: "Сөз түркүмү боюнча ашык сөздү тап" },
    options: [{ ru: "бежать", ky: "чуркоо" }, { ru: "писать", ky: "жазуу" }, { ru: "красивый", ky: "кооз" }, { ru: "читать", ky: "окуу" }],
    correctIndex: 2,
    explanation: { ru: "«Красивый» — прилагательное, остальные — глаголы.", ky: "«Кооз» — сын атооч, калгандары — этиштер." },
  },
];
