import type { Task } from "./types";
import { generatedTasks } from "./generated";
import { starTasks } from "./stars";
import { olympiadTasks } from "./olympiad";
import { varietyTasks, preWorldTasks } from "./variety";

// Задания сгруппированы по темам (topic). Часть бесплатна (free: true).
const baseTasks: Task[] = [
  // ── Логика · Найди лишнее ──────────────────────────────
  {
    id: "log-1-1",
    type: "single_choice",
    subject: "logic",
    topic: "log-odd",
    grade: 1,
    difficulty: 1,
    free: true,
    illustration: "🍎 🍐 🥕 🍌",
    prompt: { ru: "Что здесь лишнее?", ky: "Бул жерде эмне ашык?" },
    options: [
      { ru: "Яблоко", ky: "Алма" },
      { ru: "Груша", ky: "Алмурут" },
      { ru: "Морковь", ky: "Сабиз" },
      { ru: "Банан", ky: "Банан" },
    ],
    correctIndex: 2,
    explanation: {
      ru: "Морковь — это овощ, а всё остальное — фрукты.",
      ky: "Сабиз — жашылча, калгандары — мөмө-жемиштер.",
    },
  },
  {
    id: "log-odd-2",
    type: "single_choice",
    subject: "logic",
    topic: "log-odd",
    grade: 1,
    difficulty: 1,
    free: true,
    illustration: "🐶 🐱 🪑 🐰",
    prompt: { ru: "Что здесь лишнее?", ky: "Бул жерде эмне ашык?" },
    options: [
      { ru: "Собака", ky: "Ит" },
      { ru: "Кошка", ky: "Мышык" },
      { ru: "Стул", ky: "Отургуч" },
      { ru: "Заяц", ky: "Коён" },
    ],
    correctIndex: 2,
    explanation: {
      ru: "Стул — это мебель, а остальные — животные.",
      ky: "Отургуч — эмерек, калгандары — жаныбарлар.",
    },
  },
  {
    id: "log-odd-3",
    type: "single_choice",
    subject: "logic",
    topic: "log-odd",
    grade: 1,
    difficulty: 2,
    free: false,
    prompt: { ru: "Кто здесь лишний?", ky: "Бул жерде эмне ашык?" },
    options: [
      { ru: "Роза", ky: "Роза" },
      { ru: "Ромашка", ky: "Түймөгүл" },
      { ru: "Тюльпан", ky: "Кызгалдак" },
      { ru: "Яблоко", ky: "Алма" },
    ],
    correctIndex: 3,
    explanation: {
      ru: "Яблоко — это фрукт, а остальные — цветы.",
      ky: "Алма — мөмө, калгандары — гүлдөр.",
    },
  },

  // ── Логика · Закономерности ────────────────────────────
  {
    id: "log-1-2",
    type: "single_choice",
    subject: "logic",
    topic: "log-seq",
    grade: 1,
    difficulty: 1,
    free: true,
    prompt: {
      ru: "Продолжи ряд: 🔴 🔵 🔴 🔵 🔴 …",
      ky: "Катарды улант: 🔴 🔵 🔴 🔵 🔴 …",
    },
    options: [
      { ru: "🔴", ky: "🔴" },
      { ru: "🔵", ky: "🔵" },
      { ru: "🟢", ky: "🟢" },
    ],
    correctIndex: 1,
    explanation: {
      ru: "Цвета чередуются: после красного всегда идёт синий.",
      ky: "Түстөр алмашып турат: кызылдан кийин ар дайым көк келет.",
    },
  },
  {
    id: "ord-logic-1",
    type: "ordering",
    subject: "logic",
    topic: "log-seq",
    grade: 1,
    difficulty: 2,
    free: true,
    prompt: {
      ru: "Расставь по размеру: от маленького к большому",
      ky: "Өлчөмү боюнча кой: кичинесинен чоңуна",
    },
    items: [
      { ru: "🐜", ky: "🐜" },
      { ru: "🐱", ky: "🐱" },
      { ru: "🐶", ky: "🐶" },
      { ru: "🐘", ky: "🐘" },
    ],
    explanation: {
      ru: "Муравей меньше всех, а слон — самый большой.",
      ky: "Кумурска эң кичине, пил эң чоң.",
    },
  },
  {
    id: "log-seq-2",
    type: "single_choice",
    subject: "logic",
    topic: "log-seq",
    grade: 1,
    difficulty: 2,
    free: false,
    prompt: {
      ru: "Продолжи ряд: 🐱 🐶 🐱 🐶 …",
      ky: "Катарды улант: 🐱 🐶 🐱 🐶 …",
    },
    options: [
      { ru: "🐱", ky: "🐱" },
      { ru: "🐶", ky: "🐶" },
      { ru: "🐰", ky: "🐰" },
    ],
    correctIndex: 0,
    explanation: {
      ru: "Кошка и собака чередуются, дальше снова кошка.",
      ky: "Мышык менен ит алмашат, кийинки — кайра мышык.",
    },
  },

  // ── Логика · Логика и сравнение ────────────────────────
  {
    id: "log-2-1",
    type: "single_choice",
    subject: "logic",
    topic: "log-think",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: { ru: "Какое число лишнее: 2, 4, 7, 8?", ky: "Кайсы сан ашык: 2, 4, 7, 8?" },
    options: [
      { ru: "2", ky: "2" },
      { ru: "4", ky: "4" },
      { ru: "7", ky: "7" },
      { ru: "8", ky: "8" },
    ],
    correctIndex: 2,
    explanation: {
      ru: "Все числа чётные, кроме 7 — оно нечётное.",
      ky: "7ден башка бардык сандар жуп, ал эми 7 так сан.",
    },
  },
  {
    id: "log-2-2",
    type: "single_choice",
    subject: "logic",
    topic: "log-think",
    grade: 2,
    difficulty: 3,
    free: false,
    prompt: {
      ru: "Все кошки — животные. Мурка — кошка. Значит, Мурка — это…",
      ky: "Бардык мышыктар — жаныбарлар. Мурка — мышык. Демек, Мурка — бул…",
    },
    options: [
      { ru: "Животное", ky: "Жаныбар" },
      { ru: "Растение", ky: "Өсүмдүк" },
      { ru: "Машина", ky: "Машина" },
    ],
    correctIndex: 0,
    explanation: {
      ru: "Раз все кошки — животные, а Мурка кошка, то Мурка тоже животное.",
      ky: "Бардык мышыктар жаныбар болсо, Мурка да мышык, демек ал да жаныбар.",
    },
  },
  {
    id: "match-logic-1",
    type: "match_pairs",
    subject: "logic",
    topic: "log-think",
    grade: 2,
    difficulty: 2,
    free: false,
    prompt: { ru: "Соедини противоположности", ky: "Карама-каршылыктарды дал келтир" },
    left: [
      { ru: "День", ky: "Күн" },
      { ru: "Лето", ky: "Жай" },
    ],
    right: [
      { ru: "Ночь", ky: "Түн" },
      { ru: "Зима", ky: "Кыш" },
    ],
    explanation: { ru: "День — ночь, лето — зима.", ky: "Күн — түн, жай — кыш." },
  },

  // ── Математика · Счёт ──────────────────────────────────
  {
    id: "math-1-1",
    type: "number_input",
    subject: "math",
    topic: "math-count",
    grade: 1,
    difficulty: 1,
    free: true,
    illustration: "🍎🍎 ➕ 🍎🍎🍎",
    prompt: { ru: "Сколько будет 2 + 3?", ky: "2 + 3 канчага барабар?" },
    answer: 5,
    explanation: {
      ru: "К двум прибавляем три — получается пять.",
      ky: "Экиге үчтү кошсок — беш болот.",
    },
  },
  {
    id: "math-count-1",
    type: "number_input",
    subject: "math",
    topic: "math-count",
    grade: 1,
    difficulty: 1,
    free: true,
    illustration: "🍎🍎🍎🍎",
    prompt: { ru: "Сколько здесь яблок?", ky: "Бул жерде канча алма бар?" },
    answer: 4,
    explanation: { ru: "Посчитай яблоки — их четыре.", ky: "Алмаларды сана — алар төртөө." },
  },
  {
    id: "match-math-1",
    type: "match_pairs",
    subject: "math",
    topic: "math-count",
    grade: 1,
    difficulty: 1,
    free: true,
    prompt: { ru: "Соедини число и количество", ky: "Санды жана анын санын дал келтир" },
    left: [
      { ru: "2", ky: "2" },
      { ru: "3", ky: "3" },
    ],
    right: [
      { ru: "🍎🍎", ky: "🍎🍎" },
      { ru: "🍎🍎🍎", ky: "🍎🍎🍎" },
    ],
    explanation: { ru: "2 — это два яблока, 3 — три яблока.", ky: "2 — эки алма, 3 — үч алма." },
  },

  // ── Математика · Сложение и вычитание ──────────────────
  {
    id: "math-add-1",
    type: "number_input",
    subject: "math",
    topic: "math-add",
    grade: 1,
    difficulty: 1,
    free: true,
    illustration: "🍏 ➕ 🍏",
    prompt: { ru: "Сколько будет 1 + 1?", ky: "1 + 1 канчага барабар?" },
    answer: 2,
    explanation: { ru: "Одно яблоко и ещё одно — два.", ky: "Бир алма жана дагы бир — эки." },
  },
  {
    id: "math-1-2",
    type: "number_input",
    subject: "math",
    topic: "math-add",
    grade: 1,
    difficulty: 2,
    free: true,
    illustration: "🍬🍬🍬🍬🍬🍬",
    prompt: {
      ru: "У Ани было 6 конфет. 2 она съела. Сколько осталось?",
      ky: "Анада 6 конфет бар эле. 2өөнү жеди. Канчасы калды?",
    },
    answer: 4,
    explanation: {
      ru: "Из шести вычитаем две — остаётся четыре.",
      ky: "Алтыдан экини кемитсек — төртөө калат.",
    },
  },
  {
    id: "math-2-2",
    type: "number_input",
    subject: "math",
    topic: "math-add",
    grade: 1,
    difficulty: 3,
    free: false,
    prompt: { ru: "Посчитай: 3 + 4 + 2 = ?", ky: "Эсепте: 3 + 4 + 2 = ?" },
    answer: 9,
    explanation: {
      ru: "Сначала 3 + 4 = 7, затем 7 + 2 = 9.",
      ky: "Адегенде 3 + 4 = 7, анан 7 + 2 = 9.",
    },
  },

  // ── Математика · Числовые ряды ─────────────────────────
  {
    id: "ord-math-1",
    type: "ordering",
    subject: "math",
    topic: "math-seq",
    grade: 2,
    difficulty: 1,
    free: true,
    illustration: "🔢",
    prompt: {
      ru: "Расставь по порядку: от меньшего к большему",
      ky: "Ирети менен кой: кичинесинен чоңуна",
    },
    items: [
      { ru: "1", ky: "1" },
      { ru: "2", ky: "2" },
      { ru: "3", ky: "3" },
      { ru: "4", ky: "4" },
    ],
    explanation: {
      ru: "От самого маленького числа к самому большому: 1, 2, 3, 4.",
      ky: "Эң кичине сандан эң чоңуна карай: 1, 2, 3, 4.",
    },
  },
  {
    id: "math-2-1",
    type: "number_input",
    subject: "math",
    topic: "math-seq",
    grade: 2,
    difficulty: 2,
    free: false,
    prompt: { ru: "Продолжи ряд: 2, 4, 6, 8, ?", ky: "Катарды улант: 2, 4, 6, 8, ?" },
    answer: 10,
    explanation: {
      ru: "Каждое следующее число на 2 больше предыдущего.",
      ky: "Ар бир кийинки сан мурункусунан 2ге чоң.",
    },
  },
  {
    id: "math-seq-2",
    type: "number_input",
    subject: "math",
    topic: "math-seq",
    grade: 2,
    difficulty: 2,
    free: false,
    prompt: { ru: "Продолжи ряд: 5, 10, 15, ?", ky: "Катарды улант: 5, 10, 15, ?" },
    answer: 20,
    explanation: {
      ru: "Каждое число на 5 больше: 15 + 5 = 20.",
      ky: "Ар бир сан 5ке чоң: 15 + 5 = 20.",
    },
  },

  // ── Чтение · Буквы и звуки ─────────────────────────────
  {
    id: "read-1",
    type: "single_choice",
    subject: "reading",
    topic: "read-letters",
    grade: 1,
    difficulty: 1,
    free: true,
    illustration: "А → ?",
    prompt: {
      ru: "Какая буква идёт после «А»?",
      ky: "«А» тамгасынан кийин кайсы тамга келет?",
    },
    options: [
      { ru: "Б", ky: "Б" },
      { ru: "В", ky: "В" },
      { ru: "Д", ky: "Д" },
    ],
    correctIndex: 0,
    explanation: { ru: "После «А» в алфавите идёт «Б».", ky: "Алфавитте «А»дан кийин «Б» келет." },
  },
  {
    id: "read-2",
    type: "single_choice",
    subject: "reading",
    topic: "read-letters",
    grade: 1,
    difficulty: 1,
    free: true,
    prompt: { ru: "Найди гласную букву", ky: "Үндүү тамганы тап" },
    options: [
      { ru: "М", ky: "М" },
      { ru: "А", ky: "А" },
      { ru: "К", ky: "К" },
    ],
    correctIndex: 1,
    explanation: { ru: "«А» — это гласная буква.", ky: "«А» — үндүү тыбыш." },
  },

  // ── Подготовка к школе (класс 0) ──────────────────────
  {
    id: "pre-count-1",
    type: "number_input",
    subject: "math",
    topic: "pre-count",
    grade: 0,
    difficulty: 1,
    free: true,
    illustration: "🍎🍎🍎",
    prompt: { ru: "Сколько яблок?", ky: "Канча алма бар?" },
    answer: 3,
    explanation: {
      ru: "Посчитай: один, два, три — три яблока.",
      ky: "Сана: бир, эки, үч — үч алма.",
    },
  },
  {
    id: "pre-count-2",
    type: "single_choice",
    subject: "math",
    topic: "pre-count",
    grade: 0,
    difficulty: 1,
    free: true,
    illustration: "🐱🐱",
    prompt: { ru: "Сколько котят?", ky: "Канча мышык?" },
    options: [
      { ru: "1", ky: "1" },
      { ru: "2", ky: "2" },
      { ru: "3", ky: "3" },
    ],
    correctIndex: 1,
    explanation: { ru: "Котят двое — это 2.", ky: "Мышык экөө — бул 2." },
  },
  {
    id: "pre-count-3",
    type: "number_input",
    subject: "math",
    topic: "pre-count",
    grade: 0,
    difficulty: 2,
    free: false,
    illustration: "⭐⭐⭐⭐",
    prompt: { ru: "Сколько звёздочек?", ky: "Канча жылдызча?" },
    answer: 4,
    explanation: { ru: "Звёздочек четыре — это 4.", ky: "Жылдызча төртөө — бул 4." },
  },
  {
    id: "pre-more-1",
    type: "single_choice",
    subject: "math",
    topic: "pre-more",
    grade: 0,
    difficulty: 1,
    free: true,
    prompt: { ru: "Где яблок больше?", ky: "Кайда алма көп?" },
    options: [
      { ru: "🍎🍎", ky: "🍎🍎" },
      { ru: "🍎🍎🍎🍎", ky: "🍎🍎🍎🍎" },
    ],
    correctIndex: 1,
    explanation: {
      ru: "Во втором наборе яблок больше — четыре против двух.",
      ky: "Экинчи топто алма көп — экиге каршы төртөө.",
    },
  },
  {
    id: "pre-odd-1",
    type: "single_choice",
    subject: "logic",
    topic: "pre-odd",
    grade: 0,
    difficulty: 1,
    free: true,
    illustration: "🍎 🍌 ⚽ 🍐",
    prompt: { ru: "Что здесь лишнее?", ky: "Бул жерде эмне ашык?" },
    options: [
      { ru: "Яблоко", ky: "Алма" },
      { ru: "Банан", ky: "Банан" },
      { ru: "Мяч", ky: "Топ" },
      { ru: "Груша", ky: "Алмурут" },
    ],
    correctIndex: 2,
    explanation: {
      ru: "Мяч — это игрушка, а остальное — фрукты.",
      ky: "Топ — оюнчук, калгандары — мөмө.",
    },
  },
  {
    id: "pre-shapes-1",
    type: "single_choice",
    subject: "logic",
    topic: "pre-shapes",
    grade: 0,
    difficulty: 1,
    free: true,
    prompt: { ru: "Найди круг", ky: "Тегеректи тап" },
    options: [
      { ru: "🔺", ky: "🔺" },
      { ru: "🔵", ky: "🔵" },
      { ru: "⭐", ky: "⭐" },
    ],
    correctIndex: 1,
    explanation: { ru: "Круг — это 🔵.", ky: "Тегерек — бул 🔵." },
  },
  {
    id: "pre-shapes-2",
    type: "single_choice",
    subject: "logic",
    topic: "pre-shapes",
    grade: 0,
    difficulty: 1,
    free: true,
    prompt: { ru: "Найди жёлтый цвет", ky: "Сары түстү тап" },
    options: [
      { ru: "🔴", ky: "🔴" },
      { ru: "🟡", ky: "🟡" },
      { ru: "🔵", ky: "🔵" },
    ],
    correctIndex: 1,
    explanation: { ru: "Жёлтый — это 🟡.", ky: "Сары — бул 🟡." },
  },
  {
    id: "pre-letter-1",
    type: "single_choice",
    subject: "reading",
    topic: "pre-letters",
    grade: 0,
    difficulty: 1,
    free: true,
    prompt: { ru: "Найди букву А", ky: "А тамгасын тап" },
    options: [
      { ru: "Б", ky: "Б" },
      { ru: "А", ky: "А" },
      { ru: "5", ky: "5" },
    ],
    correctIndex: 1,
    explanation: { ru: "Это буква А.", ky: "Бул А тамгасы." },
  },
  {
    id: "pre-letter-2",
    type: "single_choice",
    subject: "reading",
    topic: "pre-letters",
    grade: 0,
    difficulty: 1,
    free: false,
    prompt: { ru: "Найди букву О", ky: "О тамгасын тап" },
    options: [
      { ru: "О", ky: "О" },
      { ru: "М", ky: "М" },
      { ru: "К", ky: "К" },
    ],
    correctIndex: 0,
    explanation: { ru: "Это буква О.", ky: "Бул О тамгасы." },
  },
  {
    id: "pre-count-4",
    type: "number_input",
    subject: "math",
    topic: "pre-count",
    grade: 0,
    difficulty: 1,
    free: true,
    illustration: "🐟🐟🐟🐟🐟",
    prompt: { ru: "Сколько рыбок?", ky: "Канча балык?" },
    answer: 5,
    explanation: { ru: "Рыбок пять — это 5.", ky: "Балык бешөө — бул 5." },
  },
  {
    id: "pre-count-5",
    type: "single_choice",
    subject: "math",
    topic: "pre-count",
    grade: 0,
    difficulty: 2,
    free: false,
    prompt: { ru: "Где число 3?", ky: "Кайсы жерде 3 саны?" },
    options: [
      { ru: "2", ky: "2" },
      { ru: "3", ky: "3" },
      { ru: "5", ky: "5" },
    ],
    correctIndex: 1,
    explanation: { ru: "Это число 3.", ky: "Бул — 3 саны." },
  },
  {
    id: "pre-more-2",
    type: "single_choice",
    subject: "math",
    topic: "pre-more",
    grade: 0,
    difficulty: 1,
    free: true,
    prompt: { ru: "Где конфет меньше?", ky: "Кайда конфет аз?" },
    options: [
      { ru: "🍬🍬🍬", ky: "🍬🍬🍬" },
      { ru: "🍬", ky: "🍬" },
    ],
    correctIndex: 1,
    explanation: { ru: "Одна конфета — это меньше, чем три.", ky: "Бир конфет үчтөн аз." },
  },
  {
    id: "pre-more-3",
    type: "single_choice",
    subject: "math",
    topic: "pre-more",
    grade: 0,
    difficulty: 2,
    free: false,
    prompt: { ru: "Где яблок больше?", ky: "Кайда алма көп?" },
    options: [
      { ru: "🍎🍎", ky: "🍎🍎" },
      { ru: "🍎🍎🍎", ky: "🍎🍎🍎" },
    ],
    correctIndex: 1,
    explanation: { ru: "Три яблока больше, чем два.", ky: "Үч алма экиден көп." },
  },
  {
    id: "pre-odd-2",
    type: "single_choice",
    subject: "logic",
    topic: "pre-odd",
    grade: 0,
    difficulty: 1,
    free: true,
    illustration: "🐶 🐱 🌳 🐰",
    prompt: { ru: "Что здесь лишнее?", ky: "Бул жерде эмне ашык?" },
    options: [
      { ru: "Собака", ky: "Ит" },
      { ru: "Кошка", ky: "Мышык" },
      { ru: "Дерево", ky: "Дарак" },
      { ru: "Заяц", ky: "Коён" },
    ],
    correctIndex: 2,
    explanation: {
      ru: "Дерево — растение, а остальные — животные.",
      ky: "Дарак — өсүмдүк, калгандары — жаныбарлар.",
    },
  },
  {
    id: "pre-odd-3",
    type: "single_choice",
    subject: "logic",
    topic: "pre-odd",
    grade: 0,
    difficulty: 2,
    free: false,
    illustration: "🚗 🚕 🍏 🚙",
    prompt: { ru: "Что здесь лишнее?", ky: "Бул жерде эмне ашык?" },
    options: [
      { ru: "Машина", ky: "Машина" },
      { ru: "Такси", ky: "Такси" },
      { ru: "Яблоко", ky: "Алма" },
      { ru: "Джип", ky: "Джип" },
    ],
    correctIndex: 2,
    explanation: {
      ru: "Яблоко — это фрукт, а остальное — машины.",
      ky: "Алма — мөмө, калгандары — унаалар.",
    },
  },
  {
    id: "pre-shapes-3",
    type: "single_choice",
    subject: "logic",
    topic: "pre-shapes",
    grade: 0,
    difficulty: 1,
    free: true,
    prompt: { ru: "Найди треугольник", ky: "Үч бурчтукту тап" },
    options: [
      { ru: "🔵", ky: "🔵" },
      { ru: "🔺", ky: "🔺" },
      { ru: "🟦", ky: "🟦" },
    ],
    correctIndex: 1,
    explanation: { ru: "Треугольник — это 🔺.", ky: "Үч бурчтук — 🔺." },
  },
  {
    id: "pre-shapes-4",
    type: "single_choice",
    subject: "logic",
    topic: "pre-shapes",
    grade: 0,
    difficulty: 1,
    free: true,
    prompt: { ru: "Найди красный цвет", ky: "Кызыл түстү тап" },
    options: [
      { ru: "🟢", ky: "🟢" },
      { ru: "🔴", ky: "🔴" },
      { ru: "🟡", ky: "🟡" },
    ],
    correctIndex: 1,
    explanation: { ru: "Красный — это 🔴.", ky: "Кызыл — 🔴." },
  },
  {
    id: "pre-shapes-5",
    type: "single_choice",
    subject: "logic",
    topic: "pre-shapes",
    grade: 0,
    difficulty: 2,
    free: false,
    prompt: { ru: "Найди квадрат", ky: "Чарчыны тап" },
    options: [
      { ru: "🔺", ky: "🔺" },
      { ru: "🟦", ky: "🟦" },
      { ru: "🔵", ky: "🔵" },
    ],
    correctIndex: 1,
    explanation: { ru: "Квадрат — это 🟦.", ky: "Чарчы — 🟦." },
  },
  {
    id: "pre-letter-3",
    type: "single_choice",
    subject: "reading",
    topic: "pre-letters",
    grade: 0,
    difficulty: 1,
    free: true,
    prompt: { ru: "Найди букву М", ky: "М тамгасын тап" },
    options: [
      { ru: "Н", ky: "Н" },
      { ru: "М", ky: "М" },
      { ru: "П", ky: "П" },
    ],
    correctIndex: 1,
    explanation: { ru: "Это буква М.", ky: "Бул — М тамгасы." },
  },
  {
    id: "pre-letter-4",
    type: "single_choice",
    subject: "reading",
    topic: "pre-letters",
    grade: 0,
    difficulty: 2,
    free: false,
    prompt: { ru: "Найди букву, а не цифру", ky: "Сан эмес, тамганы тап" },
    options: [
      { ru: "3", ky: "3" },
      { ru: "Б", ky: "Б" },
      { ru: "7", ky: "7" },
    ],
    correctIndex: 1,
    explanation: { ru: "Б — это буква, а 3 и 7 — цифры.", ky: "Б — тамга, 3 менен 7 — сандар." },
  },
  {
    id: "pre-count-6",
    type: "number_input",
    subject: "math",
    topic: "pre-count",
    grade: 0,
    difficulty: 1,
    free: true,
    illustration: "🎈🎈",
    prompt: { ru: "Сколько шариков?", ky: "Канча шар?" },
    answer: 2,
    explanation: { ru: "Шарика два — это 2.", ky: "Шар экөө — бул 2." },
  },
  {
    id: "pre-shapes-6",
    type: "single_choice",
    subject: "logic",
    topic: "pre-shapes",
    grade: 0,
    difficulty: 1,
    free: true,
    prompt: { ru: "Найди звезду", ky: "Жылдызды тап" },
    options: [
      { ru: "🔵", ky: "🔵" },
      { ru: "⭐", ky: "⭐" },
      { ru: "🔺", ky: "🔺" },
    ],
    correctIndex: 1,
    explanation: { ru: "Звезда — это ⭐.", ky: "Жылдыз — ⭐." },
  },
  {
    id: "pre-letter-5",
    type: "single_choice",
    subject: "reading",
    topic: "pre-letters",
    grade: 0,
    difficulty: 1,
    free: true,
    prompt: { ru: "Найди букву У", ky: "У тамгасын тап" },
    options: [
      { ru: "У", ky: "У" },
      { ru: "Н", ky: "Н" },
      { ru: "О", ky: "О" },
    ],
    correctIndex: 0,
    explanation: { ru: "Это буква У.", ky: "Бул — У тамгасы." },
  },

  // ── Подготовишка · Что дальше? ─────────────────────────
  {
    id: "pre-seq-1",
    type: "single_choice",
    subject: "logic",
    topic: "pre-seq",
    grade: 0,
    difficulty: 1,
    free: true,
    prompt: {
      ru: "Продолжи ряд: 🔴 🔵 🔴 🔵 …",
      ky: "Катарды улант: 🔴 🔵 🔴 🔵 …",
    },
    options: [
      { ru: "🔴", ky: "🔴" },
      { ru: "🔵", ky: "🔵" },
    ],
    correctIndex: 0,
    explanation: {
      ru: "После синего снова красный.",
      ky: "Көктөн кийин кайра кызыл.",
    },
  },
  {
    id: "pre-seq-2",
    type: "single_choice",
    subject: "logic",
    topic: "pre-seq",
    grade: 0,
    difficulty: 1,
    free: true,
    prompt: {
      ru: "Продолжи ряд: 🍎 🍌 🍎 🍌 …",
      ky: "Катарды улант: 🍎 🍌 🍎 🍌 …",
    },
    options: [
      { ru: "🍎", ky: "🍎" },
      { ru: "🍌", ky: "🍌" },
    ],
    correctIndex: 0,
    explanation: {
      ru: "После банана снова яблоко.",
      ky: "Банандан кийин кайра алма.",
    },
  },
  {
    id: "pre-seq-3",
    type: "single_choice",
    subject: "logic",
    topic: "pre-seq",
    grade: 0,
    difficulty: 2,
    free: false,
    prompt: {
      ru: "Продолжи ряд: ⭐ ⭐ 🌙 ⭐ ⭐ 🌙 …",
      ky: "Катарды улант: ⭐ ⭐ 🌙 ⭐ ⭐ 🌙 …",
    },
    options: [
      { ru: "⭐", ky: "⭐" },
      { ru: "🌙", ky: "🌙" },
    ],
    correctIndex: 0,
    explanation: {
      ru: "После луны снова две звезды.",
      ky: "Айдан кийин кайра эки жылдыз.",
    },
  },

  // ── Подготовишка · Большой и маленький ─────────────────
  {
    id: "pre-big-1",
    type: "single_choice",
    subject: "logic",
    topic: "pre-big",
    grade: 0,
    difficulty: 1,
    free: true,
    illustration: "🐜 🐘",
    prompt: { ru: "Кто больше?", ky: "Ким чоң?" },
    options: [
      { ru: "🐜", ky: "🐜" },
      { ru: "🐘", ky: "🐘" },
    ],
    correctIndex: 1,
    explanation: {
      ru: "Слон большой, а муравей маленький.",
      ky: "Пил чоң, кумурска кичине.",
    },
  },
  {
    id: "pre-big-2",
    type: "single_choice",
    subject: "logic",
    topic: "pre-big",
    grade: 0,
    difficulty: 1,
    free: true,
    illustration: "🏠 🐭",
    prompt: { ru: "Что меньше?", ky: "Эмне кичине?" },
    options: [
      { ru: "🏠", ky: "🏠" },
      { ru: "🐭", ky: "🐭" },
    ],
    correctIndex: 1,
    explanation: { ru: "Мышка меньше дома.", ky: "Чычкан үйдөн кичине." },
  },
  {
    id: "pre-big-3",
    type: "ordering",
    subject: "logic",
    topic: "pre-big",
    grade: 0,
    difficulty: 2,
    free: false,
    prompt: {
      ru: "Расставь от маленького к большому",
      ky: "Кичинесинен чоңуна кой",
    },
    items: [
      { ru: "🐭", ky: "🐭" },
      { ru: "🐱", ky: "🐱" },
      { ru: "🐘", ky: "🐘" },
    ],
    explanation: {
      ru: "Мышка меньше всех, а слон — самый большой.",
      ky: "Чычкан эң кичине, пил эң чоң.",
    },
  },

  // ── 1 класс · Числа до 10 ──────────────────────────────
  {
    id: "math-ten-1",
    type: "number_input",
    subject: "math",
    topic: "math-ten",
    grade: 1,
    difficulty: 2,
    free: true,
    illustration: "🍎🍎🍎🍎🍎 ➕ 🍎🍎",
    prompt: { ru: "Сколько будет 5 + 2?", ky: "5 + 2 канчага барабар?" },
    answer: 7,
    explanation: { ru: "К пяти прибавить два — семь.", ky: "Бешке экини кошсок — жети." },
  },
  {
    id: "math-ten-2",
    type: "number_input",
    subject: "math",
    topic: "math-ten",
    grade: 1,
    difficulty: 2,
    free: true,
    prompt: { ru: "Сколько будет 10 − 3?", ky: "10 − 3 канчага барабар?" },
    answer: 7,
    explanation: { ru: "Из десяти вычесть три — семь.", ky: "Ондон үчтү кемитсек — жети." },
  },
  {
    id: "math-ten-3",
    type: "single_choice",
    subject: "math",
    topic: "math-ten",
    grade: 1,
    difficulty: 2,
    free: false,
    prompt: {
      ru: "Какое число между 6 и 8?",
      ky: "6 менен 8дин ортосунда кайсы сан?",
    },
    options: [
      { ru: "5", ky: "5" },
      { ru: "7", ky: "7" },
      { ru: "9", ky: "9" },
    ],
    correctIndex: 1,
    explanation: { ru: "Между 6 и 8 стоит 7.", ky: "6 менен 8дин ортосунда 7 турат." },
  },
  {
    id: "math-ten-4",
    type: "ordering",
    subject: "math",
    topic: "math-ten",
    grade: 1,
    difficulty: 2,
    free: false,
    prompt: {
      ru: "Расставь по порядку: от меньшего к большему",
      ky: "Ирети менен кой: кичинесинен чоңуна",
    },
    items: [
      { ru: "6", ky: "6" },
      { ru: "7", ky: "7" },
      { ru: "8", ky: "8" },
      { ru: "10", ky: "10" },
    ],
    explanation: { ru: "По порядку: 6, 7, 8, 10.", ky: "Ирети менен: 6, 7, 8, 10." },
  },

  // ── 1 класс · Больше и меньше ──────────────────────────
  {
    id: "math-compare-1",
    type: "single_choice",
    subject: "math",
    topic: "math-compare",
    grade: 1,
    difficulty: 1,
    free: true,
    prompt: { ru: "Что больше: 7 или 4?", ky: "7 же 4 — кайсы чоң?" },
    options: [
      { ru: "7", ky: "7" },
      { ru: "4", ky: "4" },
    ],
    correctIndex: 0,
    explanation: { ru: "7 больше, чем 4.", ky: "7 4төн чоң." },
  },
  {
    id: "math-compare-2",
    type: "single_choice",
    subject: "math",
    topic: "math-compare",
    grade: 1,
    difficulty: 1,
    free: true,
    prompt: { ru: "Что меньше: 9 или 3?", ky: "9 же 3 — кайсы кичине?" },
    options: [
      { ru: "9", ky: "9" },
      { ru: "3", ky: "3" },
    ],
    correctIndex: 1,
    explanation: { ru: "3 меньше, чем 9.", ky: "3 9дан кичине." },
  },
  {
    id: "math-compare-3",
    type: "single_choice",
    subject: "math",
    topic: "math-compare",
    grade: 1,
    difficulty: 2,
    free: false,
    prompt: { ru: "Поставь знак: 5 … 5", ky: "Белги кой: 5 … 5" },
    options: [
      { ru: "＞", ky: "＞" },
      { ru: "＜", ky: "＜" },
      { ru: "＝", ky: "＝" },
    ],
    correctIndex: 2,
    explanation: { ru: "5 равно 5 — знак «＝».", ky: "5 5ке барабар — «＝» белгиси." },
  },

  // ── 1 класс · Гласные и согласные ──────────────────────
  {
    id: "rv-1",
    type: "single_choice",
    subject: "reading",
    topic: "read-vowels",
    grade: 1,
    difficulty: 2,
    free: true,
    prompt: { ru: "Найди гласную букву", ky: "Үндүү тамганы тап" },
    options: [
      { ru: "М", ky: "М" },
      { ru: "У", ky: "У" },
      { ru: "К", ky: "К" },
    ],
    correctIndex: 1,
    explanation: { ru: "У — гласная буква.", ky: "У — үндүү тамга." },
  },
  {
    id: "rv-2",
    type: "single_choice",
    subject: "reading",
    topic: "read-vowels",
    grade: 1,
    difficulty: 2,
    free: true,
    prompt: { ru: "Найди согласную букву", ky: "Үнсүз тамганы тап" },
    options: [
      { ru: "А", ky: "А" },
      { ru: "Н", ky: "Н" },
      { ru: "О", ky: "О" },
    ],
    correctIndex: 1,
    explanation: { ru: "Н — согласная буква.", ky: "Н — үнсүз тамга." },
  },
  {
    id: "rv-3",
    type: "single_choice",
    subject: "reading",
    topic: "read-vowels",
    grade: 1,
    difficulty: 3,
    free: false,
    prompt: {
      ru: "Сколько гласных: А, Б, О, В?",
      ky: "Канча үндүү: А, Б, О, В?",
    },
    options: [
      { ru: "1", ky: "1" },
      { ru: "2", ky: "2" },
      { ru: "3", ky: "3" },
    ],
    correctIndex: 1,
    explanation: {
      ru: "Гласные — А и О, их две.",
      ky: "Үндүүлөр — А жана О, экөө.",
    },
  },

  // ── 1 класс · уплотнение существующих тем ──────────────
  {
    id: "log-odd-4",
    type: "single_choice",
    subject: "logic",
    topic: "log-odd",
    grade: 1,
    difficulty: 1,
    free: true,
    illustration: "🪑 🛋️ 🛏️ 🐱",
    prompt: { ru: "Что здесь лишнее?", ky: "Бул жерде эмне ашык?" },
    options: [
      { ru: "Стул", ky: "Отургуч" },
      { ru: "Диван", ky: "Диван" },
      { ru: "Кровать", ky: "Керебет" },
      { ru: "Кот", ky: "Мышык" },
    ],
    correctIndex: 3,
    explanation: {
      ru: "Кот — животное, а остальное — мебель.",
      ky: "Мышык — жаныбар, калгандары — эмерек.",
    },
  },
  {
    id: "log-seq-3",
    type: "single_choice",
    subject: "logic",
    topic: "log-seq",
    grade: 1,
    difficulty: 1,
    free: true,
    prompt: {
      ru: "Продолжи ряд: 🌞 🌙 🌞 🌙 …",
      ky: "Катарды улант: 🌞 🌙 🌞 🌙 …",
    },
    options: [
      { ru: "🌞", ky: "🌞" },
      { ru: "🌙", ky: "🌙" },
    ],
    correctIndex: 0,
    explanation: {
      ru: "Солнце и луна чередуются — дальше солнце.",
      ky: "Күн менен ай алмашат — андан ары күн.",
    },
  },
  {
    id: "math-count-2",
    type: "number_input",
    subject: "math",
    topic: "math-count",
    grade: 1,
    difficulty: 1,
    free: true,
    illustration: "🐱",
    prompt: { ru: "Сколько лап у кошки?", ky: "Мышыктын канча буту бар?" },
    answer: 4,
    explanation: { ru: "У кошки четыре лапы.", ky: "Мышыктын төрт буту бар." },
  },
  {
    id: "math-add-2",
    type: "number_input",
    subject: "math",
    topic: "math-add",
    grade: 1,
    difficulty: 2,
    free: true,
    prompt: { ru: "Сколько будет 7 − 2?", ky: "7 − 2 канчага барабар?" },
    answer: 5,
    explanation: { ru: "Из семи вычесть два — пять.", ky: "Жетиден экини кемитсек — беш." },
  },
  {
    id: "read-3",
    type: "single_choice",
    subject: "reading",
    topic: "read-letters",
    grade: 1,
    difficulty: 2,
    free: false,
    prompt: {
      ru: "Какая буква идёт перед «Б»?",
      ky: "«Б» тамгасынан мурун кайсы тамга келет?",
    },
    options: [
      { ru: "А", ky: "А" },
      { ru: "В", ky: "В" },
      { ru: "Г", ky: "Г" },
    ],
    correctIndex: 0,
    explanation: { ru: "Перед «Б» идёт «А».", ky: "«Б»дан мурун «А» келет." },
  },

  // ── 2 класс · Числа до 100 ─────────────────────────────
  {
    id: "math-tens-1",
    type: "number_input",
    subject: "math",
    topic: "math-tens",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: { ru: "Сколько будет 10 + 5?", ky: "10 + 5 канчага барабар?" },
    answer: 15,
    explanation: { ru: "Десять и ещё пять — пятнадцать.", ky: "Он жана дагы беш — он беш." },
  },
  {
    id: "math-tens-2",
    type: "number_input",
    subject: "math",
    topic: "math-tens",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: { ru: "Сколько будет 20 − 4?", ky: "20 − 4 канчага барабар?" },
    answer: 16,
    explanation: { ru: "Из двадцати вычесть четыре — шестнадцать.", ky: "Жыйырмадан төрттү кемитсек — он алты." },
  },
  {
    id: "math-tens-3",
    type: "single_choice",
    subject: "math",
    topic: "math-tens",
    grade: 2,
    difficulty: 2,
    free: false,
    prompt: { ru: "Сколько десятков в числе 30?", ky: "30 санында канча ондук бар?" },
    options: [
      { ru: "2", ky: "2" },
      { ru: "3", ky: "3" },
      { ru: "5", ky: "5" },
    ],
    correctIndex: 1,
    explanation: { ru: "30 — это три десятка.", ky: "30 — үч ондук." },
  },
  {
    id: "math-tens-4",
    type: "ordering",
    subject: "math",
    topic: "math-tens",
    grade: 2,
    difficulty: 2,
    free: false,
    prompt: {
      ru: "Расставь по порядку: от меньшего к большему",
      ky: "Ирети менен кой: кичинесинен чоңуна",
    },
    items: [
      { ru: "10", ky: "10" },
      { ru: "20", ky: "20" },
      { ru: "30", ky: "30" },
      { ru: "40", ky: "40" },
    ],
    explanation: { ru: "По порядку: 10, 20, 30, 40.", ky: "Ирети менен: 10, 20, 30, 40." },
  },

  // ── 2 класс · Умножение ────────────────────────────────
  {
    id: "math-mult-1",
    type: "number_input",
    subject: "math",
    topic: "math-mult",
    grade: 2,
    difficulty: 3,
    free: true,
    illustration: "🍎🍎 🍎🍎 🍎🍎",
    prompt: { ru: "Сколько будет 2 × 3?", ky: "2 × 3 канчага барабар?" },
    answer: 6,
    explanation: { ru: "По два три раза — шесть.", ky: "Экиден үч жолу — алты." },
  },
  {
    id: "math-mult-2",
    type: "number_input",
    subject: "math",
    topic: "math-mult",
    grade: 2,
    difficulty: 3,
    free: true,
    prompt: { ru: "Сколько будет 5 × 2?", ky: "5 × 2 канчага барабар?" },
    answer: 10,
    explanation: { ru: "По пять два раза — десять.", ky: "Бештен эки жолу — он." },
  },
  {
    id: "math-mult-3",
    type: "single_choice",
    subject: "math",
    topic: "math-mult",
    grade: 2,
    difficulty: 3,
    free: false,
    prompt: { ru: "2 × 4 — это…", ky: "2 × 4 — бул…" },
    options: [
      { ru: "2 + 2 + 2 + 2", ky: "2 + 2 + 2 + 2" },
      { ru: "2 + 4", ky: "2 + 4" },
      { ru: "4 + 4", ky: "4 + 4" },
    ],
    correctIndex: 0,
    explanation: {
      ru: "Умножить на 4 — сложить два четыре раза.",
      ky: "4кө көбөйтүү — экини төрт жолу кошуу.",
    },
  },

  // ── 2 класс · Задачи ───────────────────────────────────
  {
    id: "math-word-1",
    type: "number_input",
    subject: "math",
    topic: "math-word",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: {
      ru: "У Пети было 8 конфет, 3 он отдал. Сколько осталось?",
      ky: "Петяда 8 конфет бар эле, 3үн берди. Канчасы калды?",
    },
    answer: 5,
    explanation: { ru: "8 − 3 = 5.", ky: "8 − 3 = 5." },
  },
  {
    id: "math-word-2",
    type: "number_input",
    subject: "math",
    topic: "math-word",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: {
      ru: "На ветке 4 птицы, прилетели ещё 3. Сколько стало?",
      ky: "Бутакта 4 куш бар, дагы 3 келди. Канча болду?",
    },
    answer: 7,
    explanation: { ru: "4 + 3 = 7.", ky: "4 + 3 = 7." },
  },
  {
    id: "math-word-3",
    type: "number_input",
    subject: "math",
    topic: "math-word",
    grade: 2,
    difficulty: 3,
    free: false,
    prompt: {
      ru: "В коробке 10 карандашей, забрали 6. Сколько осталось?",
      ky: "Кутучада 10 карандаш бар, 6сын алды. Канчасы калды?",
    },
    answer: 4,
    explanation: { ru: "10 − 6 = 4.", ky: "10 − 6 = 4." },
  },

  // ── 2 класс · Слова и предложения ──────────────────────
  {
    id: "rw2-1",
    type: "single_choice",
    subject: "reading",
    topic: "read-words",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: { ru: "«дом» — это слово или буква?", ky: "«үй» — сөзбү же тамгабы?" },
    options: [
      { ru: "Слово", ky: "Сөз" },
      { ru: "Буква", ky: "Тамга" },
    ],
    correctIndex: 0,
    explanation: { ru: "«дом» — это слово из трёх букв.", ky: "«үй» — эки тамгадан турган сөз." },
  },
  {
    id: "rw2-2",
    type: "number_input",
    subject: "reading",
    topic: "read-words",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: {
      ru: "Сколько слов в предложении: «Кот спит»?",
      ky: "«Мышык уктайт» сүйлөмүндө канча сөз?",
    },
    answer: 2,
    explanation: { ru: "Два слова: «кот» и «спит».", ky: "Эки сөз: «мышык» жана «уктайт»." },
  },
  {
    id: "rw2-3",
    type: "single_choice",
    subject: "reading",
    topic: "read-words",
    grade: 2,
    difficulty: 3,
    free: false,
    prompt: { ru: "Найди имя (пишется с большой буквы)", ky: "Атты тап (баш тамга менен жазылат)" },
    options: [
      { ru: "кот", ky: "мышык" },
      { ru: "Аня", ky: "Айна" },
      { ru: "стол", ky: "үстөл" },
    ],
    correctIndex: 1,
    explanation: { ru: "Имена людей пишут с большой буквы.", ky: "Адамдардын аттары баш тамга менен жазылат." },
  },

  // ── 2 класс · уплотнение существующих тем ──────────────
  {
    id: "log-think-4",
    type: "single_choice",
    subject: "logic",
    topic: "log-think",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: { ru: "Какое число лишнее: 3, 5, 8, 9?", ky: "Кайсы сан ашык: 3, 5, 8, 9?" },
    options: [
      { ru: "3", ky: "3" },
      { ru: "5", ky: "5" },
      { ru: "8", ky: "8" },
      { ru: "9", ky: "9" },
    ],
    correctIndex: 2,
    explanation: {
      ru: "8 — чётное, а 3, 5, 9 — нечётные.",
      ky: "8 — жуп, ал эми 3, 5, 9 — так сандар.",
    },
  },
  {
    id: "math-seq-3",
    type: "number_input",
    subject: "math",
    topic: "math-seq",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: { ru: "Продолжи ряд: 10, 20, 30, ?", ky: "Катарды улант: 10, 20, 30, ?" },
    answer: 40,
    explanation: { ru: "Каждое число на 10 больше: 30 + 10 = 40.", ky: "Ар бир сан 10го чоң: 30 + 10 = 40." },
  },

  // ── 2 класс · уплотнение (второй проход) ───────────────
  {
    id: "log-think-5",
    type: "single_choice",
    subject: "logic",
    topic: "log-think",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: {
      ru: "Все рыбы плавают. Карась — рыба. Значит, карась…",
      ky: "Бардык балыктар сүзөт. Карп — балык. Демек, карп…",
    },
    options: [
      { ru: "Плавает", ky: "Сүзөт" },
      { ru: "Летает", ky: "Учат" },
      { ru: "Бегает", ky: "Чуркайт" },
    ],
    correctIndex: 0,
    explanation: {
      ru: "Раз все рыбы плавают, то и карась плавает.",
      ky: "Бардык балыктар сүзсө, карп да сүзөт.",
    },
  },
  {
    id: "log-think-6",
    type: "single_choice",
    subject: "logic",
    topic: "log-think",
    grade: 2,
    difficulty: 3,
    free: false,
    prompt: {
      ru: "Что тяжелее: 1 кг ваты или 1 кг железа?",
      ky: "Эмне оор: 1 кг мамык же 1 кг темир?",
    },
    options: [
      { ru: "Вата", ky: "Мамык" },
      { ru: "Железо", ky: "Темир" },
      { ru: "Одинаково", ky: "Бирдей" },
    ],
    correctIndex: 2,
    explanation: { ru: "1 кг есть 1 кг — вес одинаковый.", ky: "1 кг — бул 1 кг, салмагы бирдей." },
  },
  {
    id: "math-seq-4",
    type: "number_input",
    subject: "math",
    topic: "math-seq",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: { ru: "Продолжи ряд: 5, 10, 15, 20, ?", ky: "Катарды улант: 5, 10, 15, 20, ?" },
    answer: 25,
    explanation: { ru: "Каждое число на 5 больше: 20 + 5 = 25.", ky: "Ар бир сан 5ке чоң: 20 + 5 = 25." },
  },
  {
    id: "math-seq-5",
    type: "number_input",
    subject: "math",
    topic: "math-seq",
    grade: 2,
    difficulty: 3,
    free: false,
    prompt: { ru: "Продолжи ряд: 100, 90, 80, ?", ky: "Катарды улант: 100, 90, 80, ?" },
    answer: 70,
    explanation: { ru: "Каждое число на 10 меньше: 80 − 10 = 70.", ky: "Ар бир сан 10го кичине: 80 − 10 = 70." },
  },
  {
    id: "math-tens-5",
    type: "number_input",
    subject: "math",
    topic: "math-tens",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: { ru: "Сколько будет 30 + 40?", ky: "30 + 40 канчага барабар?" },
    answer: 70,
    explanation: { ru: "Три десятка и четыре десятка — семь десятков.", ky: "Үч ондук жана төрт ондук — жети ондук." },
  },
  {
    id: "math-tens-6",
    type: "single_choice",
    subject: "math",
    topic: "math-tens",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: { ru: "Что больше: 45 или 54?", ky: "Кайсы чоң: 45 же 54?" },
    options: [
      { ru: "45", ky: "45" },
      { ru: "54", ky: "54" },
    ],
    correctIndex: 1,
    explanation: { ru: "54 больше, чем 45.", ky: "54 45төн чоң." },
  },
  {
    id: "math-mult-4",
    type: "number_input",
    subject: "math",
    topic: "math-mult",
    grade: 2,
    difficulty: 3,
    free: true,
    prompt: { ru: "Сколько будет 3 × 3?", ky: "3 × 3 канчага барабар?" },
    answer: 9,
    explanation: { ru: "По три три раза — девять.", ky: "Үчтөн үч жолу — тогуз." },
  },
  {
    id: "math-mult-5",
    type: "number_input",
    subject: "math",
    topic: "math-mult",
    grade: 2,
    difficulty: 3,
    free: false,
    prompt: { ru: "Сколько будет 4 × 2?", ky: "4 × 2 канчага барабар?" },
    answer: 8,
    explanation: { ru: "По четыре два раза — восемь.", ky: "Төрттөн эки жолу — сегиз." },
  },
  {
    id: "math-word-4",
    type: "number_input",
    subject: "math",
    topic: "math-word",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: {
      ru: "В вазе 6 яблок и 4 груши. Сколько всего фруктов?",
      ky: "Вазада 6 алма жана 4 алмурут. Баары канча мөмө?",
    },
    answer: 10,
    explanation: { ru: "6 + 4 = 10.", ky: "6 + 4 = 10." },
  },
  {
    id: "math-word-5",
    type: "number_input",
    subject: "math",
    topic: "math-word",
    grade: 2,
    difficulty: 3,
    free: false,
    prompt: {
      ru: "У Ани было 12 наклеек, 5 она отдала. Сколько осталось?",
      ky: "Айнада 12 стикер бар эле, 5ин берди. Канчасы калды?",
    },
    answer: 7,
    explanation: { ru: "12 − 5 = 7.", ky: "12 − 5 = 7." },
  },
  {
    id: "rw2-4",
    type: "number_input",
    subject: "reading",
    topic: "read-words",
    grade: 2,
    difficulty: 2,
    free: true,
    prompt: {
      ru: "Сколько слов в предложении: «Мама моет раму»?",
      ky: "«Апам терезени жууйт» сүйлөмүндө канча сөз?",
    },
    answer: 3,
    explanation: { ru: "Три слова: «мама», «моет», «раму».", ky: "Үч сөз: «апам», «терезени», «жууйт»." },
  },
  {
    id: "rw2-5",
    type: "single_choice",
    subject: "reading",
    topic: "read-words",
    grade: 2,
    difficulty: 3,
    free: false,
    prompt: {
      ru: "Найди слово, которое обозначает действие",
      ky: "Иш-аракетти билдирген сөздү тап",
    },
    options: [
      { ru: "стол", ky: "үстөл" },
      { ru: "бежит", ky: "чуркайт" },
      { ru: "красный", ky: "кызыл" },
    ],
    correctIndex: 1,
    explanation: {
      ru: "«бежит» отвечает на вопрос «что делает?» — это действие.",
      ky: "«чуркайт» — «эмне кылат?» деген суроого жооп берет, бул иш-аракет.",
    },
  },
];

// starTasks идут последними — «задание со звёздочкой» замыкает каждую тему.
export const tasks: Task[] = [
  ...baseTasks,
  ...generatedTasks,
  ...starTasks,
  ...olympiadTasks,
  ...preWorldTasks,
  ...varietyTasks,
];

export function getTasks(filter?: {
  subject?: Task["subject"];
  topic?: string;
  grade?: Task["grade"];
  freeOnly?: boolean;
}): Task[] {
  return tasks.filter((task) => {
    if (filter?.subject && task.subject !== filter.subject) return false;
    if (filter?.topic && task.topic !== filter.topic) return false;
    if (filter?.grade && task.grade !== filter.grade) return false;
    if (filter?.freeOnly && !task.free) return false;
    return true;
  });
}
